In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import matplotlib.pyplot as plt 

import geopandas as gpd  # manejo de datos georefereciados
from geopandas import GeoSeries # series de datos georerenciados
from shapely.geometry import Point, LineString, Polygon, MultiLineString # objetos geométricos
from pyproj import CRS, Geod # proyecciones a sistemas planares
import googlemaps #google request  

from tqdm import tqdm # contador de tiempo en un loop
from matplotlib.lines import Line2D
import swifter # parallel procesing
import unidecode 

import warnings
warnings.filterwarnings('ignore') # eliminar warning messages

In [12]:
data = pd.read_stata(r"../../data/geopandas_data/Sample_Denuncia_de_Delitos_2017.dta")
data

,index,FUENTE,ID_DENUNCIA,ID_N,UBIGEO_CIA,NOMBREDD,NOMBREPP,NOMBREDI,UBIGEO_HECHO,IH201,...,IH211_17,IH211_18,IH211_19,IH211_20,IH211_21,IH211_22,IH211_23,IH211_24,IH211_24_O,IH212
0,0,1.0,1.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
1,1,1.0,2.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100605,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
2,2,1.0,3.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
3,3,1.0,4.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
4,4,1.0,5.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,1.0,996.0,0012,200104,Piura,PIURA,CASTILLA,200104,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
996,996,1.0,997.0,0012,200104,Piura,PIURA,CASTILLA,200104,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
997,997,1.0,998.0,0012,200104,Piura,PIURA,CASTILLA,200104,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
998,998,1.0,999.0,0012,200104,Piura,PIURA,CASTILLA,200104,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
999,999,1.0,1000.0,0012,200104,Piura,PIURA,CASTILLA,200104,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0

In [13]:
data2017 = data.copy()

In [14]:
# NOMBREDI : nombre del distrito
# IH205_DD: codigo de 2 digitos del departamento (callao : 07)
# H206: TIPO DE VIA DONDE OCURRIÓ EL DELITO
# IH207_B: NOMBRE DE LA DE VÍA DONDE OCURRIÓ EL DELITO
# IH207_A: Nº CUADRA DONDE OCURRIÓ EL DELITO

data2017[['NOMBREDI','H206','IH207_B','IH207_A']]

      NOMBREDI  H206                        IH207_B IH207_A
0    RUPA-RUPA   2.0                   MAR DE PLATA      SN
1    RUPA-RUPA   7.0                        LUYANDO      SN
2    RUPA-RUPA   1.0                       RAYMONDI      SN
3    RUPA-RUPA   1.0                       RAYMONDI      SN
4    RUPA-RUPA   2.0                       CHICLAYO      SN
..         ...   ...                            ...     ...
995   CASTILLA   7.0                 URB MIRAFLORES      SN
996   CASTILLA   7.0                 URB MIRAFLORES      SN
997   CASTILLA   7.0                 URB MIRAFLORES      SN
998   CASTILLA   7.0  AH LOS LIBERTADORES  II ETAPA      SN
999   CASTILLA   7.0  ASOCIACION PAMPAS DE CASTILLA      SN

[1000 rows x 4 columns]

In [15]:
data2017.IH207_A.unique()

array(['SN', '6', '5', '2', '282', '11', '601', '878', '811', '343',
       '201', '114', '392', '7', '403', '1', '184', '420', '469', '296',
       '237', '501', '4', '340', '17', '9', '12', '10', '15', '8', '431',
       '297', '3', '14', '446', '1012', '198', '970', '1732', '18',
       '1001', '315', '990', '13', '571', '390', '937', '244', '774',
       '645', '615', '450', '813', '573'], dtype=object)

In [16]:
# filtro callaro y selecciono las primeras 20 observaciones 

callao = data2017.iloc[0:20]
callao[['NOMBREDI','H206','IH207_B','IH207_A']]

     NOMBREDI  H206                   IH207_B IH207_A
0   RUPA-RUPA   2.0              MAR DE PLATA      SN
1   RUPA-RUPA   7.0                   LUYANDO      SN
2   RUPA-RUPA   1.0                  RAYMONDI      SN
3   RUPA-RUPA   1.0                  RAYMONDI      SN
4   RUPA-RUPA   2.0                  CHICLAYO      SN
5   RUPA-RUPA   1.0              ALAMEDA PERU      SN
6   RUPA-RUPA   1.0              ALAMEDA PERU      SN
7   RUPA-RUPA   1.0              ALAMEDA PERU      SN
8   RUPA-RUPA   4.0               LA LIBERTAD      SN
9   RUPA-RUPA   1.0              ALAMEDA PERU      SN
10  RUPA-RUPA   1.0               28 DE JULIO      SN
11  RUPA-RUPA   1.0                  RAYMONDI      SN
12  RUPA-RUPA   1.0                  AMAZONAS      SN
13  RUPA-RUPA   5.0    TINGO MARIA A PUCALLPA      SN
14  RUPA-RUPA   5.0  TINGO MARIA A NARANJILLO      SN
15  RUPA-RUPA   1.0                  RAYMONDI      SN
16  RUPA-RUPA   7.0                 SAN JORGE      SN
17  RUPA-RUPA   7.0                 SAN JORGE      SN
18  RUPA-RUPA   2.0                  PUCALLPA      SN
19  RUPA-RUPA   1.0              LOS CLAVELES      SN

In [17]:
#COMISARÃA BELLAVISTA : erro por no reconocer tilde. Se aplica unicode para corregirlo 

callao['IH207_B'] = callao['IH207_B'].apply( lambda x : unidecode.unidecode( x ) ) # unicode para corregir tildes no detectados
callao

,index,FUENTE,ID_DENUNCIA,ID_N,UBIGEO_CIA,NOMBREDD,NOMBREPP,NOMBREDI,UBIGEO_HECHO,IH201,...,IH211_17,IH211_18,IH211_19,IH211_20,IH211_21,IH211_22,IH211_23,IH211_24,IH211_24_O,IH212
0,0,1.0,1.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
1,1,1.0,2.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100605,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
2,2,1.0,3.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
3,3,1.0,4.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
4,4,1.0,5.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,1.0
5,5,1.0,6.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
6,6,1.0,7.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
7,7,1.0,8.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
8,8,1.0,9.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
9,9,1.0,10.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
10,10,1.0,11.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
11,11,1.0,12.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,1.0
12,12,1.0,13.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
13,13,1.0,14.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,1.0
14,14,1.0,15.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
15,15,1.0,16.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
16,16,1.0,17.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,,1.0
17,17,1.0,18.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0
18,18,1.0,19.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,1.0
19,19,1.0,20.0,0001,100601,Huánuco,LEONCIO PRADO,RUPA-RUPA,100601,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,1.0

In [18]:
# Free geocoding 

coordinates = gpd.tools.geocode("PUCP Peru, Avenida Universitaria, 15032, San Miguel, Lima")
coordinates
# Point(x,y): x: longitud, y:latitud

,geometry,address
0,POINT (-77.07894 -12.07281),"Cafetería CeprePucp, Avenida Universitaria, 15..."

In [19]:
coordinates['address'][0]

'Cafetería CeprePucp, Avenida Universitaria, 15032, Avenida Universitaria, San Miguel, Lima, Perú'

In [20]:
# Google API

gmaps = googlemaps.Client( key = 'AIzaSyA-Cj5npW0l2P7bZKP6WmQSq4uXSMvfHCM' ) 
# se crea el objeto gmaps con el token de permiso
    
result_api = gmaps.geocode( "PUCP, Avenida Universitaria, 15032, San Miguel, Lima" , region = 'PE' ) # region = PE 
result_api

# Google devuelve las solicitudes en formato Json

[{'address_components': [{'long_name': '1801',
    'short_name': '1801',
    'types': ['street_number']},
   {'long_name': 'Avenida Universitaria',
    'short_name': 'Av. Universitaria',
    'types': ['route']},
   {'long_name': 'Fund Pando',
    'short_name': 'Fund Pando',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': 'San Miguel',
    'short_name': 'San Miguel',
    'types': ['locality', 'political']},
   {'long_name': 'Provincia de Lima',
    'short_name': 'Provincia de Lima',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'Provincia de Lima',
    'short_name': 'Provincia de Lima',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Peru',
    'short_name': 'PE',
    'types': ['country', 'political']},
   {'long_name': '15088', 'short_name': '15088', 'types': ['postal_code']}],
  'formatted_address': 'Av. Universitaria 1801, San Miguel 15088, Peru',
  'geometry': {'location': {'lat': -12.0687255, 'lng': -77.0781351},
   'location_type': 'ROOFTOP',
   'viewport': {'northeast': {'lat': -12.0673181697085,
     'lng': -77.0768696197085},
    'southwest': {'lat': -12.0700161302915, 'lng': -77.07956758029151}}},
  'partial_match': True,
  'place_id': 'ChIJpUAI1BLJBZERLobll7e_oNc',
  'plus_code': {'compound_code': 'WWJC+GP San Miguel',
   'global_code': '57V4WWJC+GP'},
  'types': ['establishment', 'point_of_interest', 'university']},
 {'address_components': [{'long_name': '15032',
    'short_name': '15032',
    'types': ['street_number']},
   {'long_name': 'Avenida Universitaria',
    'short_name': 'Av. Universitaria',
    'types': ['route']},
   {'long_name': 'Urb Villa Sol Etapa 2',
    'short_name': 'Urb Villa Sol Etapa 2',
    'types': ['political', 'sublocality', 'sublocality_level_1']},
   {'long_name': 'Lima',
    'short_name': 'Lima',
    'types': ['locality', 'political']},
   {'long_name': 'Provincia de Lima',
    'short_name': 'Provincia de Lima',
    'types': ['administrative_area_level_2', 'political']},
   {'long_name': 'Provincia de Lima',
    'short_name': 'Provincia de Lima',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'Peru',
    'short_name': 'PE',
    'types': ['country', 'political']},
   {'long_name': '15304', 'short_name': '15304', 'types': ['postal_code']}],
  'formatted_address': 'Av. Universitaria 15032, Lima 15304, Peru',
  'geometry': {'location': {'lat': -11.9640121, 'lng': -77.0695123},
   'location_type': 'RANGE_INTERPOLATED',
   'viewport': {'northeast': {'lat': -11.9626631197085,
     'lng': -77.06816331970849},
    'southwest': {'lat': -11.9653610802915, 'lng': -77.07086128029151}}},
  'partial_match': True,
  'place_id': 'EilBdi4gVW5pdmVyc2l0YXJpYSAxNTAzMiwgTGltYSAxNTMwNCwgUGVydSIxEi8KFAoSCeUG8yklzgWREfJuHMIV-fCfELh1KhQKEgnN4lnRx84FkRFHtqagqJGWFA',
  'types': ['street_address']}]

In [21]:
result_api[0]

{'address_components': [{'long_name': '1801',
   'short_name': '1801',
   'types': ['street_number']},
  {'long_name': 'Avenida Universitaria',
   'short_name': 'Av. Universitaria',
   'types': ['route']},
  {'long_name': 'Fund Pando',
   'short_name': 'Fund Pando',
   'types': ['political', 'sublocality', 'sublocality_level_1']},
  {'long_name': 'San Miguel',
   'short_name': 'San Miguel',
   'types': ['locality', 'political']},
  {'long_name': 'Provincia de Lima',
   'short_name': 'Provincia de Lima',
   'types': ['administrative_area_level_2', 'political']},
  {'long_name': 'Provincia de Lima',
   'short_name': 'Provincia de Lima',
   'types': ['administrative_area_level_1', 'political']},
  {'long_name': 'Peru', 'short_name': 'PE', 'types': ['country', 'political']},
  {'long_name': '15088', 'short_name': '15088', 'types': ['postal_code']}],
 'formatted_address': 'Av. Universitaria 1801, San Miguel 15088, Peru',
 'geometry': {'location': {'lat': -12.0687255, 'lng': -77.0781351},
  'location_type': 'ROOFTOP',
  'viewport': {'northeast': {'lat': -12.0673181697085,
    'lng': -77.0768696197085},
   'southwest': {'lat': -12.0700161302915, 'lng': -77.07956758029151}}},
 'partial_match': True,
 'place_id': 'ChIJpUAI1BLJBZERLobll7e_oNc',
 'plus_code': {'compound_code': 'WWJC+GP San Miguel',
  'global_code': '57V4WWJC+GP'},
 'types': ['establishment', 'point_of_interest', 'university']}

In [22]:
result_api[0].keys()

dict_keys(['address_components', 'formatted_address', 'geometry', 'partial_match', 'place_id', 'plus_code', 'types'])

In [23]:
result_api[0]['geometry']['location']

{'lat': -12.0687255, 'lng': -77.0781351}

In [24]:
lat = result_api[0]['geometry']['location']['lat']
lon = result_api[0]['geometry']['location']['lng']  
(lon,lat)

(-77.0781351, -12.0687255)

In [25]:
result_api[0]['types']

['establishment', 'point_of_interest', 'university']

In [26]:
# componentes de la dirección 

result_api[0]['address_components'][4]

{'long_name': 'Provincia de Lima',
 'short_name': 'Provincia de Lima',
 'types': ['administrative_area_level_2', 'political']}

In [27]:
callao[['NOMBREDI','H206','IH207_B','IH207_A']]

     NOMBREDI  H206                   IH207_B IH207_A
0   RUPA-RUPA   2.0              MAR DE PLATA      SN
1   RUPA-RUPA   7.0                   LUYANDO      SN
2   RUPA-RUPA   1.0                  RAYMONDI      SN
3   RUPA-RUPA   1.0                  RAYMONDI      SN
4   RUPA-RUPA   2.0                  CHICLAYO      SN
5   RUPA-RUPA   1.0              ALAMEDA PERU      SN
6   RUPA-RUPA   1.0              ALAMEDA PERU      SN
7   RUPA-RUPA   1.0              ALAMEDA PERU      SN
8   RUPA-RUPA   4.0               LA LIBERTAD      SN
9   RUPA-RUPA   1.0              ALAMEDA PERU      SN
10  RUPA-RUPA   1.0               28 DE JULIO      SN
11  RUPA-RUPA   1.0                  RAYMONDI      SN
12  RUPA-RUPA   1.0                  AMAZONAS      SN
13  RUPA-RUPA   5.0    TINGO MARIA A PUCALLPA      SN
14  RUPA-RUPA   5.0  TINGO MARIA A NARANJILLO      SN
15  RUPA-RUPA   1.0                  RAYMONDI      SN
16  RUPA-RUPA   7.0                 SAN JORGE      SN
17  RUPA-RUPA   7.0                 SAN JORGE      SN
18  RUPA-RUPA   2.0                  PUCALLPA      SN
19  RUPA-RUPA   1.0              LOS CLAVELES      SN

In [28]:
# crear el tipo de calle 

# condiciones

filt1 = callao['H206'] == 1
filt2 = callao['H206'] == 2
filt3 = callao['H206'] == 3
filt4 = callao['H206'] == 4
filt5 = callao['H206'] == 5
filt6 = callao['H206'] == 6
filt7 = callao['H206'] == 7

# se filtra, se crea la vafriable tipo_calle y se asigno valores 
callao.loc[filt1, 'tipo_calle'] = "Avenida"
callao.loc[filt2, 'tipo_calle'] = "Jiron"
callao.loc[filt3, 'tipo_calle'] = "Calle"
callao.loc[filt4, 'tipo_calle'] = "Pasaje"
callao.loc[filt5, 'tipo_calle'] = "Carretera"
callao.loc[filt6, 'tipo_calle'] = "Prolongación"
callao.loc[filt7, 'tipo_calle'] = " "

callao.replace({'IH207_B': "SN", 'IH207_A': "SN"}, " ", inplace = True)

In [29]:
callao[['NOMBREDI','H206','tipo_calle','IH207_B','IH207_A']]

     NOMBREDI  H206 tipo_calle                   IH207_B IH207_A
0   RUPA-RUPA   2.0      Jiron              MAR DE PLATA
1   RUPA-RUPA   7.0                              LUYANDO
2   RUPA-RUPA   1.0    Avenida                  RAYMONDI
3   RUPA-RUPA   1.0    Avenida                  RAYMONDI
4   RUPA-RUPA   2.0      Jiron                  CHICLAYO
5   RUPA-RUPA   1.0    Avenida              ALAMEDA PERU
6   RUPA-RUPA   1.0    Avenida              ALAMEDA PERU
7   RUPA-RUPA   1.0    Avenida              ALAMEDA PERU
8   RUPA-RUPA   4.0     Pasaje               LA LIBERTAD
9   RUPA-RUPA   1.0    Avenida              ALAMEDA PERU
10  RUPA-RUPA   1.0    Avenida               28 DE JULIO
11  RUPA-RUPA   1.0    Avenida                  RAYMONDI
12  RUPA-RUPA   1.0    Avenida                  AMAZONAS
13  RUPA-RUPA   5.0  Carretera    TINGO MARIA A PUCALLPA
14  RUPA-RUPA   5.0  Carretera  TINGO MARIA A NARANJILLO
15  RUPA-RUPA   1.0    Avenida                  RAYMONDI
16  RUPA-RUPA   7.0                            SAN JORGE
17  RUPA-RUPA   7.0                            SAN JORGE
18  RUPA-RUPA   2.0      Jiron                  PUCALLPA
19  RUPA-RUPA   1.0    Avenida              LOS CLAVELES

In [48]:
# function to geocode

def georef_geocode( row ):
       
    address = f"{row['tipo_calle']} {row['IH207_B']} {row['IH207_A']}, {row['NOMBREDI']}, Callao, Perú"
    
    geo = gpd.tools.geocode(address)
    
    # Information
    
    try:
        lat = geo['geometry'].y[0]
        lon = geo['geometry'].x[0]  
        
    except Exception as e:
        
        lat = np.nan
        lon = np.nan
    
    return ( lat, lon )

# function to Geocoding Google API


def georef_google_api( row ):
       
    address = f"{row['tipo_calle']} {row['IH207_B']} {row['IH207_A']}, {row['NOMBREDI']}, Callao, Perú"
    
    # Set Geolocation
    
    gmaps = googlemaps.Client( key = 'AIzaSyB_eg_oDNudLcXLgvr3Xu3f67UlXIKKXLM' )
    
    result_api = gmaps.geocode( address , region = 'PE' )
    
    # Information
    try:
        lat = result_api[0]['geometry']['location']['lat']
        lon = result_api[0]['geometry']['location']['lng']   
        
    except Exception :
        
        
        lat = np.nan
        lon = np.nan
    
    return ( lat, lon )

In [52]:
callao['coordinates_geo'] = callao.swifter.apply( lambda x: georef_geocode( x )  , axis = 1 )  # apply function by each row
callao['coordinates_google'] = callao.swifter.apply( lambda x: georef_google_api( x )  , axis = 1 )  # apply function by each row

Pandas Apply:   0%|          | 0/20 [00:00<?, ?it/s]

In [53]:
callao[['lat_geo', 'lng_geo']] = pd.DataFrame(callao.coordinates_geo.tolist() ,  index = callao.index )
callao[['lat_google', 'lng_google']] = pd.DataFrame(callao.coordinates_google.tolist() ,  index = callao.index )

In [54]:
callao[['tipo_calle','IH207_B','IH207_A','lat_geo', 'lng_geo','lat_google', 'lng_google']]

,tipo_calle,IH207_B,IH207_A,lat_geo,lng_geo,lat_google,lng_google
0,Jiron,MAR DE PLATA,,-6.062613,-77.176112,-12.050849,-77.125984
1,,LUYANDO,,NaN,NaN,-9.164573,-76.155187
2,Avenida,RAYMONDI,,-9.106612,-76.149221,-9.164573,-76.155187
3,Avenida,RAYMONDI,,-9.106612,-76.149221,-9.164573,-76.155187
4,Jiron,CHICLAYO,,-11.943829,-77.132402,-9.164573,-76.155187
5,Avenida,ALAMEDA PERU,,-12.000958,-77.116582,-9.164573,-76.155187
6,Avenida,ALAMEDA PERU,,-12.000958,-77.116582,-9.164573,-76.155187
7,Avenida,ALAMEDA PERU,,-12.000958,-77.116582,-9.164573,-76.155187
8,Pasaje,LA LIBERTAD,,-8.104969,-79.021897,-12.050849,-77.125984
9,Avenida,ALAMEDA PERU,,-12.000958,-77.116582,-9.164573,-76.155187
10,Avenida,28 DE JULIO,,-8.605619,-77.148348,-9.164573,-76.155187
11,Avenida,RAYMONDI,,-9.106612,-76.149221,-9.164573,-76.155187
12,Avenida,AMAZONAS,,-11.824521,-77.153297,-9.164573,-76.155187
13,Carretera,TINGO MARIA A PUCALLPA,,-9.106612,-76.149221,-9.297647,-76.000020
14,Carretera,TINGO MARIA A NARANJILLO,,-9.106612,-76.149221,-9.297647,-76.000020
15,Avenida,RAYMONDI,,-9.106612,-76.149221,-9.164573,-76.155187
16,,SAN JORGE,,-15.004711,-74.086880,-12.050849,-77.125984
17,,SAN JORGE,,-15.004711,-74.086880,-12.050849,-77.125984
18,Jiron,PUCALLPA,,-9.940917,-76.244198,-9.164573,-76.155187
19,Avenida,LOS CLAVELES,,-9.288967,-75.982694,-12.050849,-77.125984