In [3]:
import numpy as np
import pandas as pd

#Se crea la función
def funcionEscalamiento(vector):
    return list(map(lambda x: (x-np.min(vector))/(np.max(vector)-np.min(vector)), vector))

#Probando la función a 100 números aleatorios
vectorAleatorio=np.random.rand(100)*100
funcionEscalamiento(vectorAleatorio)
##

#Probando la función a las columnas numéricas de la base de datos de compras de consumidores
data= pd.read_csv(r'../../data/BDD_compras_consumidores.csv',delimiter=';')
columnasNumericas = data[['Fresh', 'Milk', 'Grocery', 'Frozen', 'Detergents_Paper', 'Delicatessen']]
columnas_escaladas = columnasNumericas.apply(funcionEscalamiento)
columnas

     Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
0    12669   9656     7561     214              2674          1338
1     7057   9810     9568    1762              3293          1776
2     6353   8808     7684    2405              3516          7844
3    13265   1196     4221    6404               507          1788
4    22615   5410     7198    3915              1777          5185
..     ...    ...      ...     ...               ...           ...
435  29703  12051    16027   13135               182          2204
436  39228   1431      764    4510                93          2346
437  14531  15488    30243     437             14841          1867
438  10290   1981     2232    1038               168          2125
439   2787   1698     2510      65               477            52

[440 rows x 6 columns]

In [43]:
#Función que calcula el factorial

def funcionFactorial(n):
    n_anterior= n - 1
    factorial= n
    while n_anterior >= 1:
        factorial=factorial*n_anterior
        if n_anterior==1: break
        n_anterior=n_anterior-1
    return(f"El factorial de {n} es: {factorial}")
   
funcionFactorial(5) #Se invoca la funciónFactorial

'El factorial de 5 es: 120'

In [37]:
#Se crea la funcion de Índice de Masa Corporal
def funcionMasaCorporal(peso, talla):
    imc = peso / (talla**2)
    if 18.5 <= imc <= 24.9:
        clasificacion = "Normal"
    elif 25 <= imc <= 29.9:
        clasificacion = "Sobrepeso"
    elif 30 <= imc <= 34.9 :
        clasificacion = "Obesidad grado I"
    elif 35 <= imc <= 39.9 :
        clasificacion = "Obesidad grado II"
    else:
        clasificacion = "Obesidad grado III"
    
    return (print("El estudiante con peso", peso, "y talla", talla, "tiene", imc, "y clasificación", clasificacion))
    
#Se prueban los resultados para los estudiantes
funcionMasaCorporal(70,1.50) #Estudiante 1

funcionMasaCorporal(85,1.80) #Estudiante 2

funcionMasaCorporal(50,1.60) #Estudiante 3

El estudiante con peso 70 y talla 1.5 tiene 31.11111111111111 y clasificación Obesidad grado I
El estudiante con peso 85 y talla 1.8 tiene 26.234567901234566 y clasificación Sobrepeso
El estudiante con peso 50 y talla 1.6 tiene 19.531249999999996 y clasificación Normal

In [26]:
#Función que calcula el coeficiente de correlación de Pearson y la varianza del portafolio
import pandas as pd
import numpy as np
portfolio = pd.read_csv(r'../../data/Portafolio.csv')
def funcionActivosFinancieros(data):
    X = data['X']
    y = data['Y']
    coef_pearson = (np.cov(X,y)[0][1])/((np.var(X)*np.var(y))**(1/2))
    var_portafolio = ((0.2)**2)*np.var(X) + ((0.8)**2)*np.var(y) + 2*0.2*0.8*np.cov(X,y)[0][1]
    
    return (print("El coeficiente de correlación de pearson es",coef_pearson,"y la varianza del portafolio es",var_portafolio))
funcionActivosFinancieros(portfolio)

El coeficiente de correlación de pearson es 0.5206743364408886 y la varianza del portafolio es 1.07402815110268

In [58]:
#Funcion que permite keywords especiales
import numpy as np
def funcionEspecial( *args, **kwargs):
    
      
    if ( kwargs[ 'metodo' ] == "escalamiento" ) :
        
        return list(map(lambda x: (x-np.min(args))/(np.max(args)-np.min(args)), args)) #Si se elige escalamiento
    
    elif ( kwargs[ 'metodo' ] == "inverse hyperbolic sine" ) :

        return list(map(lambda x: np.log(x + np.sqrt(x**2 + 1)), args)) #Si se elige inverse hyperbolic sine
    else:
        raise ValueError( f"The function argument {kwargs[ 'metodo' ]} is not supported." )
        
        # Mensaje de error porque el metodo no existe

    
#Se prueba la funcion segun el metodo elegido
print(funcionEspecial( 4, 5, 6, 7, 8, metodo = "escalamiento" ), "\n")

print(funcionEspecial( 4, 5, 6, metodo = "inverse hyperbolic sine" ), "\n")



######################

[0.0, 0.25, 0.5, 0.75, 1.0]

[2.0947125472611012, 2.3124383412727525, 2.4917798526449118]