In [243]:
import pandas as pd
import numpy as np
import re  # for regular expressions (REGEX)
import os  # for directorio
import unidecode # to drop tildes
from datetime import datetime  # library for time
import warnings
import math
warnings.filterwarnings('ignore')

In [89]:
data = pd.read_excel("../../data/Centro_salud/Centro_salud_mental.xls") # Subir base de datos
data

,Departamento,Provincia,Distrito,UBIGEO_string,UBIGEO_numero,dirección,Institución_ruc,fecha_apertura,GPS,Resolucion,Telefono,horario,presupuesto
0,CALLAO,CALLAO,LA PERLA,70104,70104,AVENIDA LA PAZ CUADRA 3 LA PERLA CALLAO CALLAO...,GOBIERNO REONAL 20147907487,28/06/15 :00:00,"@-12.14,-74.561!ayay%6",DS-023-2015 PCM,telf: 145-36985,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
1,LIMA,LIMA,RIMAC,150128,150128,Calle Los Virreyes 205. Urbanización El Manzan...,MINS 20602217508,01/10/2015,"@-12.14,-74.56!ayay%7",DS-024-2015 PCM,telf: 145-36986,"apertura 8:00 am time, 17:00pm","ses1,255,546S/."
2,AREQUIPA,AREQUIPA,JOSE LUIS BUSTAMANTE Y RIVERO,40129,40129,AVENIDA CARACAS NÚMERO 807 URBANIZACIÓN SIMÓN ...,GOBIERNO REGIONAL 20172661794,00/00/00,"@-12.151,-74.5615!ayay%8",DS-012-2014 MINSA,telf: 145-36987,"apertura 9:00 am time, 16:00pm","soles1,255,546S/. dolares300,125$"
3,LIMA,LIMA,COMAS,150110,150110,Los Rosales Mz G8 Lt 02 altura de la 33 de la ...,MNSA 20602217508,10/07/2018,"@-12.14,-74.12!ayay%9",DS-026-2016 PCM,telf: 45-3,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
4,LA LIBERTAD,TRUJILLO,EL PORVENIR,130102,130102,Mz Z1 Antenor Orrego - Rio Seco. Ref. Casa Bla...,GOBIERNO REG 20218911189,28/08/2018,"@-12.1,-74.5615!ayay%10",DS-023-2015 MINSA,telf: 145-36989,"apertura 8:15 am time, 16:30pm","soles1,255,546S/. Dólares300,125$"
5,LA LIBERTAD,TRUJILLO,FLORENCIA DE MORA,130103,130103,CALLE 20 DE JUNIO CUADRA 09 BARRIO 06 S/N FLO...,GOBIERNO REGIONAL 20218911189,02/11/2018,"@-12.140,-74.5615!ayay%11",DS-027-2015 PCM,telf: 145-36990,"apertura 8:00 am time, 16:00pm","soes1,255,546S/. Dólares300,125$"
6,LA LIBERTAD,TRUJILLO,EL PORVENIR,130102,103102,OTROS MANUEL UBALDE NÚMERO 679 DISTRITO EL POR...,GOBIER EGIOAL 20218911189,31/12/2018,"@-12.14,-74.5615!ayay%12",DS-028-2015 PCM,NaN,"apertura 8:00 am time, 18:00pm","soles1,255,546S/. Dóles300,125$"
7,LA LIBERTAD,TRUJILLO,TRUJILLO,130101,130101,AVENIDA CESAR VALLEJO/ MZ 45 AA. HH. HUERTA BE...,GOBIERNO REGIONAL 20218911189,01/07/19 :00:00,"@-12.13,-74.69!ayay%13",DS-029-2016 MINSA,telf: 145-36992,"apertura 9:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
8,APURIMAC,ANDAHUAYLAS,TALAVERA,30216,30216,AVENIDA 28 DE JULIO 296 1 AL COSTADO DEL MERCA...,GOBIERNO GIONAL 20199917928,01/10/2019,"@-12.14,-74.5615!ayay%14",DS-030-2014 PCM,telf: 145-36993,"apertura 8:00 am time, 16:30pm","soles1,255,546S/. Dólares300,125$"
9,LORETO,LORETO,NAUTA,160301,160301,CALLE MARAÑON NÚMERO S/N DISTRITO NAUTA PROVIN...,GOBIERNO REGIONAL,10/10/2019,"@-12.14,-74.5615!ayay%15",DS-024-2012 PCM,telf: 145-36994,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
10,LIMA,LIMA,VILLA EL SALVADOR,150142,150142,OTROS SECTOR 6 GRUPO 5 I 19 AV PASTOR SEVILLA...,MINSA 20602251641,05/11/2019,"@-12.14,-74.5615!ayay%16",DS-030-2015 PCM,telf: 145-36995,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
11,LIMA,LIMA,LA VICTORIA,150115,150115,JIRÓN ANTONIO BAZO CDRA. 12 S/N CRUCE DE JIRÓN...,MINSA 20602250602,15/11/2019,"@-12.14,-74.5615!ayay%17",DS-031-2015 PCM,telf: 145-36996,"apertura 8:45 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
12,AREQUIPA,CASTILLA,APLAO,40401,40401,OTROS ANEXO LA REAL PLAZA PRINCIPAL NÚMERO SIN...,GOBIERNO REGIONAL 20172661794,00/00/00,"@-12.14,-74.5615!ayay%18",DS-032-2015 PCM,telf: 145-36997,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
13,CUSCO,CALCA,CALCA,80401,80401,JIRÓN GRAU S/N 1 DETRAS DE LA MUNICIPALIDAD DE...,GOBIERNO REGIONAL 20490215850,15/12/2019,"@-12.14,-74.5615!ayay%19",DS-033-2015 MINSA,telf: 145-36998,"apertura 8:00 am time, 16:00pm","sos1,255,546S/. Dólas300,125$"
14,CUSCO,CUSCO,SAN SEBASTIAN,80105,80105,CALLE ESMERALDA S/N 1 JUNTO A L COMPAÑIA DE BO...,GOBIERNO REGIONAL 20450736539,26/06/2020,"@-12.14,-74.5615!ayay%20",DS-034-2015 PCM,telf: 145-36999,"apertura 9:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
15,PUNO,SAN ROMAN,JULIACA,211101,211101,Jr. Pentagono s/n Ureb. Taparachi sector III d...,GOBIERNO REGIONAL 20145686548,01/10/2020,"@-12.14,-74.5615!ayay%21",DS-035-2015 PCM,telf: 145-37000,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
16,LA LIBERTAD,SANCHEZ CARRION,HUAMACHUCO,130901,130901,JIRÓN SUAREZ 1145 AL COSTADO DEL TERMINAL DE M...,GOBIERNO REGIONAL 20222308080,01/10/2020,NaN,DS-036-2015 PCM,telf: 145-37001,"apertura 8:00 am time, 16:30pm","soles1,255,546S/."
17,LIMA,LIMA,LOS OLIVOS,150117,150117,Jr. Hualcan Mz G Lte. 3B Urb. Palas Reales. Lo...,MINzA 20602217508,02/11/20 :00:00,"@-12.14,-74.5615!ayay%23",DS-037-2015 PCM,telf: 145-37002,"apertura 10:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
18,PIURA,PAITA,PAITA,200501,200501,Asentamiento Humano Alan Garcia ZP s/n ex Hosp...,GOBIERNO REGIONAL 20199565398,02/11/2020,"@-12.14,-74.5615!ayay%24",DS-038-2015 PCM,telf:,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
19,MADRE DE DIOS,TAMBOPATA,TAMBOPATA,170101,170101,JIRÓN IGNACIO MERINO NÚMERO S/N DISTRITO TAMBO...,GOBIERNO REGIONAL 20170258054,03/11/2020,"@-12.14,-74.5615!ayay%25",DS-039-2015 MINSA,telf: 145-37004,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
20,TUMBES,TUMBES,TUMBES,240101,240101,OTROS VIRGEN DEL CISNE ASENTAMIENTO HUMANO L 0...,GOBIERNO REGIONAL 20171001065,04/11/2020 !%&,"@-12.14,-74.5615!ayay%26",DS-040-2015 PCM,telf: 145-37005,"apertura 7:00 am time, 15:00pm","soles1,255,546S/. Dólares300,125$"
21,CAJAMARCA,CUTERVO,CUTERVO,60601,60601,Centro Recreacional Tomas Gálvez Quispe distri...,GOBIERNO REGIONAL 20165645325,04/11/2020,"@-12.14,-74.3!ayay%27",DS-041-2015 MINSA,telf: 145-37006,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
22,HUANUCO,LEONCIO PRADO,RUPA-RUPA,100601,100601,Av. Chiclayo N°781-Tingo María DIST...,GOBIERNO REGIONAL 20489252601,11/11/2020,"@-12.14,-74.5615!ayay%28",DS-042-2015 PCM,telf: 145-37007,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
23,HUANUCO,PACHITEA,PANAO,100801,100801,JIRÓN BOLOGNESI NÚMERO 158 PISO 1 DISTRITO PAN...,GOBIERNO REGIONAL 20602799973,00/00/00,"@-12.14,-74.5615!ayay%29",DS-043-2015 MINSA,telf: 145-37008,"apertura 10:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
24,AREQUIPA,CAYLLOMA,MAJES,40520,40520,OTROS PROLONGACIÓN CAMINO CARROZABLE MANZANA J...,GOBIERNO REGIONAL 20172661794,13/11/2020,"@-12.14,-74.5615!ayay%30",DS-044-2015 PCM,telf: 145-37009,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
25,CAJAMARCA,CAJAMARCA,CAJAMARCA,60101,60101,AVENIDA ALFONSO UGARTE 1133 A UNA CUADRA DEL C...,GOBIERNO REGIONAL 20603980248,14/11/2020,"@-12.14,-74.5615!ayay%31",DS-045-2015 PCM,telf: 145-37010,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
26,PASCO,OXAPAMPA,OXAPAMPA,190301,190301,JIRÓN KENNEDY 1444 OXAPAMPA OXAPAMPA PASCO di...,GOBIERNO REGIONAL 20191045671,15/11/2020,"@-12.14,-74.5615!ayay%32",DS-046-2015 PCM,telf: 145-37011,"apertura 8:15 am time, 16:00pm","soles1,255,546S/."
27,CUSCO,CUSCO,SANTIAGO,80106,80106,PASAJE RDO. PADRE MANYA S/N ANTIGUO TERMINAL D...,GOBIERNO REGIONAL 20490215850,19/11/2020,"@-12.14,-74.5615!ayay%33",DS-047-2015 MINSA,telf: 145-37012,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
28,LIMA,LIMA,LIMA,150101,150101,JIRÓN GERMAN AMEZAGA 375 Al lado de la clinica...,MINSA 20602250602,01/12/2020,"@-12.16,-74.5615!ayay%34",DS-048-2015 PCM,NaN,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
29,MADRE DE DIOS,TAMBOPATA,INAMBARI,170102,170102,JIRÓN FRANCISCO BOLOGNESI CON JR ALFONSO UGART...,GOBIERNO REGIONAL 20170258054,15/06/21 :00:00,NaN,DS-049-2015 PCM,telf: 145-37014,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
30,LORETO,ALTO AMAZONAS,YURIMAGUAS,160201,160201,CALLE JOSÉ RIERA N° 339 DISTRITO YURIMAGUAS...,GOBIERNO REGIONAL 20450241564,29/06/2021,"@-12.14,-74.5615!ayay%36",DS-050-2015 MINSA,telf: 145-37015,"apertura 8:30 am time, 16:30pm","soles1,255,546S/. Dóles300,125$"
31,ICA,ICA,SALAS,110108,110108,OTROS CENTRO POBLADO NUESTRA SEÑORA DE GUADALU...,REGIONAL 20171178585,08/08/2021,"@-12.14,-74.5615!ayay%37",DS-051-2015 PCM,telf: 145-37016,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
32,LAMBAYEQUE,LAMBAYEQUE,ILLIMO,140303,140303,PARQUE 22 DE NOVIEMBRE DE ILLIMO NÚMERO 00 PIS...,GOBIERNO REGIONAL 20163833094,00/00/00,"@-12.19,-74.5615!ayay%38",DS-052-2015 PCM,telf: 145-37017,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
33,ANCASH,HUARAZ,INDEPENDENCIA,20105,20105,Av. Antonio Raymondi N°111 distrito INDEPENDEN...,GOBIERNO REGIONAL 20156003817,12/11/2021,"@-12.14,-74.5615!ayay%39",DS-053-2015 PCM,telf: 145-37018,"apertura 8:45 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
34,LIMA,CAÑETE,IMPERIAL,150507,150507,"Predio Rural Cerro Alegre , Asociación Popular...",GOBIERNO REGIONAL,01/01/2019,"@-12.14,-74.5615!ayay%40",DS-054-2015 PCM,telf: 145-37019,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
35,LIMA,LIMA,CHORRILLOS,150108,150108,JIRÓN GENERAL BUENDIA 503 VILLA MILITAR OESTE ...,MIA 20602251641,01/02/2021,"@-12.14,-74.5615!ayay%41",DS-055-2015 PCM,telf: 145-37020,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
36,APURIMAC,ABANCAY,CURAHUASI,30104,30104,AVENIDA LOS ROSALES NÚMERO S/N PISO 1 DISTRITO...,GOBIERNO REGIONAL 20491240742,03/01/2020,"@-12.14,-74.5615!ayay%42",DS-056-2015 PCM,telf: 145-37021,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
37,SAN MARTIN,TOCACHE,TOCACHE,221001,221001,JIRÓN PEDRO GOMEZ 07 ANTIGUO HOSPITAL TOCACHE ...,GOBIERNO REGIONAL 20531320574,01/04/2019,NaN,DS-057-2015 MINSA,telf: 145-37022,"apertura 8:30 am time, 17:00pm","soles1,255,546S/."
38,AREQUIPA,CAMANA,CAMANA,40201,40201,CALLE LA MERCED SUB LOTE A DISTRITO CAMANA PRO...,GOBIERNO REGIONAL 20167237895,01/06/15 :00:00,"@-12.14,-73.5615!ayay%44",DS-058-2015 PCM,telf: 145-37023,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
39,PUNO,SAN ROMAN,JULIACA,211101,211101,PASAJE Las Violetas MANZANA A1 LOTE 05 URBANIZ...,GOBIER GIONAL 20145686548,01/06/2015,"@-12.14,-74.5615!ayay%45",DS-059-2015 PCM,telf: 145-37024,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
40,PUNO,SAN ROMAN,JULIACA,211101,211101,JIRÓN JUAN VELASCO ALVARADO CON ATAHUALLPA NÚM...,GOBIERNO REGIONAL 20145686548,01/06/2015,"@-12.14,-74.5615!ayay%46",DS-060-2015 MINSA,telf:,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
41,PUNO,SAN ROMAN,SAN MIGUEL,211105,211105,JIRÓN AEROPUERTO NÚMERO 266 URBANIZACIÓN SAN J...,GOBIERNO REGIONAL 20145686548,01/06/2015,"@-12.14,-74.5615!ayay%47",DS-062-2015 PCM,telf: 145-37026,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
42,JUNIN,YAULI,LA OROYA,120801,120801,CARRETERA CENTRAL DISTRITO LA OROYA PROVINCIA ...,GOBIEEGIONAL 20156176240,01/06/2018,"@-12.14,-74.5615!ayay%48",DS-063-2015 PCM,telf: 145-37027,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
43,AYACUCHO,CANGALLO,LOS MOROCHUCOS,50203,50203,JIRÓN 9 DE DICIEMBRE S/N PAMPA CANGALLO (PLAZ...,GOBIERNO REGIONAL 20452308992,01/06/2021,"@-12.14,-74.9!ayay%49",DS-064-2015 MINSA,telf: 145-37028,"apertura 8:00 am time, 16:450pm","sos1,255,546S/. Dólares300,125$"
44,JUNIN,HUANCAYO,CHILCA,120107,120107,CALLE REAL 100 1 ENTRE FERROCARRIL Y REAL CHIL...,GOBIERNO REGIONAL 20486391279,01/07/17 !%&,"@-12.14,-74.5615!ayay%50",DS-065-2015 PCM,telf: 145-37029,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
45,LIMA,LIMA,PUEBLO LIBRE,150121,150121,JIRÓN JJ PASOS 394 PUEBLO LIBRE LIMA LIMA dis...,MSA 20602250602,01/07/2018,"@-12.14,-74.5615!ayay%51",DS-06-2015 PCM,telf: 145-37030,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
46,AREQUIPA,ISLAY,COCACHACRA,40702,40702,CALLE INCA GARCILAZO MANZANA H LOTE 7 URBANIZA...,GOBIERNO REGIONAL 20172661794,01/08/2015,NaN,DS-067-2015 PCM,telf: 145-37031,"apertura 9:00 am time, 16:30pm","soles1,255,546S/."
47,TUMBES,ZARUMILLA,ZARUMILLA,240301,240301,AVENIDA LA MARINA S/N CAMPO AMOR ZARUMILLA ZAR...,REGIONAL 20171001065,01/08/2018,"@-12.14,-74.5615!ayay%53",DS-068-2015 PCM,telf: 145-37032,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
48,CAJAMARCA,CHOTA,CHOTA,60401,60401,CALLE ACCESO ALBERGUE INFANTIL A CINCUENTA MET...,GOBIERNO REGIONAL 20411038506,01/08/2018,"@-12.14,-74.5615!ayay%54",DS-069-2015 PCM,telf: 145-37033,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólas300,125$"
49,ICA,NAZCA,VISTA ALEGRE,110305,110305,CALLE CENTENARIO CON TUPAC YUPANQUI NÚMERO S/N...,GOBIERONAL 20171178585,00/00/00,"@-12.14,-74.5615!ayay%55",DS-070-2015 MINSA,telf:,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
50,LIMA,HUAURA,HUACHO,150801,150801,CALLE 14 DE NOVIEMBRE MANZANARES I ETAPA S/N H...,GOBIERNO REGIONAL 20162197461,01/08/2018,"@-12.14,-74.5615!ayay%56",DS-071-2015 PCM,telf: 145-37035,"apertura 8:00 am time, 16:00pm","ses1,255,546S/. Dólares300,125$"
51,HUANCAVELICA,HUANCAVELICA,HUANCAVELICA,90101,90101,"JIRÓN JR. 8 DE OCTUBRE S/N, HUANCAVELICA, HUA...",GOBIERNO REGIONAL 20600985206,01/08/2019,"@-12.14,-74.5615!ayay%57",DS-072-2015 PCM,telf: 145-37036,"apertura 9:00 am time, 17:00pm","soles1,255,546S/. Dólares300,125$"
52,LIMA,LIMA,SANTA ANITA,150137,150137,AVENIDA MARIA PARADO DE BELLIDO 1031 COOPERATI...,MINSA 20602236596,01/09/2018,"@-12.14,-74.5615!ayay%58",DS-073-2015 PCM,telf: 145-37037,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
53,ICA,PALPA,PALPA,110401,110401,Calle independecia s/n . Ref. antes del Hospit...,GOBIERNO REGIONAL 20534791381,01/10/2018 :00:00,"@-12.14,-74.5615!ayay%59",DS-074-2015 MINSA,NaN,"apertura 8:00 am time, 16:00pm","soles1,255,546S/."
54,LORETO,DATEM DEL MARAÑON,BARRANCA,160701,160701,PASAJE MATEO PUMACAHUA S/N BARRANCA distrito B...,GOBIERNO ONAL 20528442154,01/10/2019,"@-12.14,-74.5615!ayay%60",DS-075-2015 PCM,telf: 145-37039,"apertura 8:00 am time, 16:00pm","soles1,255,546S/. Dólares300,125$"
55,PUNO,HUANCANE,HUANCANE,210601,210601,AVENIDA MANUEL H. CORNEJO NÚMERO 603 DISTRITO ...,GERNO REGIONAL 20363839500,01/10/2019 :00:00,"@-12.14,-74.5115!ayay%61",DS-076-2015 PCM,telf: 145-37040,"apertura 10:00 am time, 18:00pm","soles1,255,546S/. Dólares300,125$"

In [90]:
 # from capital letters to lower 

data.columns = data.columns.str.lower()

# map es el loop replacement que permite aplicar la función str.lower a cada elemento de la lista data.columns

In [91]:
data.columns

Index(['departamento', 'provincia', 'distrito', 'ubigeo_string',
       'ubigeo_numero', 'dirección', 'institución_ruc', 'fecha_apertura',
       'gps', 'resolucion', 'telefono', 'horario', 'presupuesto'],
      dtype='object')

##  1.0 extraccción de texto

### re.sub()

In [92]:
data['institución_ruc']

0       GOBIERNO REONAL 20147907487
1                  MINS 20602217508
2     GOBIERNO REGIONAL 20172661794
3                  MNSA 20602217508
4          GOBIERNO REG 20218911189
5     GOBIERNO REGIONAL 20218911189
6         GOBIER EGIOAL 20218911189
7     GOBIERNO REGIONAL 20218911189
8       GOBIERNO GIONAL 20199917928
9                GOBIERNO REGIONAL
10                MINSA 20602251641
11                MINSA 20602250602
12    GOBIERNO REGIONAL 20172661794
13    GOBIERNO REGIONAL 20490215850
14    GOBIERNO REGIONAL 20450736539
15    GOBIERNO REGIONAL 20145686548
16    GOBIERNO REGIONAL 20222308080
17                MINzA 20602217508
18    GOBIERNO REGIONAL 20199565398
19    GOBIERNO REGIONAL 20170258054
20    GOBIERNO REGIONAL 20171001065
21    GOBIERNO REGIONAL 20165645325
22    GOBIERNO REGIONAL 20489252601
23    GOBIERNO REGIONAL 20602799973
24    GOBIERNO REGIONAL 20172661794
25    GOBIERNO REGIONAL 20603980248
26    GOBIERNO REGIONAL 20191045671
27    GOBIERNO REGIONAL 20490215850
28                MINSA 20602250602
29    GOBIERNO REGIONAL 20170258054
30    GOBIERNO REGIONAL 20450241564
31             REGIONAL 20171178585
32    GOBIERNO REGIONAL 20163833094
33    GOBIERNO REGIONAL 20156003817
34               GOBIERNO REGIONAL
35                  MIA 20602251641
36    GOBIERNO REGIONAL 20491240742
37    GOBIERNO REGIONAL 20531320574
38    GOBIERNO REGIONAL 20167237895
39        GOBIER GIONAL 20145686548
40    GOBIERNO REGIONAL 20145686548
41    GOBIERNO REGIONAL 20145686548
42         GOBIEEGIONAL 20156176240
43    GOBIERNO REGIONAL 20452308992
44    GOBIERNO REGIONAL 20486391279
45                  MSA 20602250602
46    GOBIERNO REGIONAL 20172661794
47             REGIONAL 20171001065
48    GOBIERNO REGIONAL 20411038506
49           GOBIERONAL 20171178585
50    GOBIERNO REGIONAL 20162197461
51    GOBIERNO REGIONAL 20600985206
52                MINSA 20602236596
53    GOBIERNO REGIONAL 20534791381
54        GOBIERNO ONAL 20528442154
55       GERNO REGIONAL 20363839500
Name: institución_ruc, dtype: object

In [93]:
# Extraer solo texto de una celda que contiene numero y texto 

# import re

data['inst1'] = data['institución_ruc'].apply(lambda x: re.sub('[0-9]','',x))

 # re.sub de susbstitución
# se va a subtituir cada digito por nada. Se va a eliminar cada digito

data['inst1']

0       GOBIERNO REONAL
1                  MINS
2     GOBIERNO REGIONAL
3                  MNSA
4          GOBIERNO REG
5     GOBIERNO REGIONAL
6         GOBIER EGIOAL
7     GOBIERNO REGIONAL
8       GOBIERNO GIONAL
9     GOBIERNO REGIONAL
10                MINSA
11                MINSA
12    GOBIERNO REGIONAL
13    GOBIERNO REGIONAL
14    GOBIERNO REGIONAL
15    GOBIERNO REGIONAL
16    GOBIERNO REGIONAL
17                MINzA
18    GOBIERNO REGIONAL
19    GOBIERNO REGIONAL
20    GOBIERNO REGIONAL
21    GOBIERNO REGIONAL
22    GOBIERNO REGIONAL
23    GOBIERNO REGIONAL
24    GOBIERNO REGIONAL
25    GOBIERNO REGIONAL
26    GOBIERNO REGIONAL
27    GOBIERNO REGIONAL
28                MINSA
29    GOBIERNO REGIONAL
30    GOBIERNO REGIONAL
31             REGIONAL
32    GOBIERNO REGIONAL
33    GOBIERNO REGIONAL
34    GOBIERNO REGIONAL
35                  MIA
36    GOBIERNO REGIONAL
37    GOBIERNO REGIONAL
38    GOBIERNO REGIONAL
39        GOBIER GIONAL
40    GOBIERNO REGIONAL
41    GOBIERNO REGIONAL
42         GOBIEEGIONAL
43    GOBIERNO REGIONAL
44    GOBIERNO REGIONAL
45                  MSA
46    GOBIERNO REGIONAL
47             REGIONAL
48    GOBIERNO REGIONAL
49           GOBIERONAL
50    GOBIERNO REGIONAL
51    GOBIERNO REGIONAL
52                MINSA
53    GOBIERNO REGIONAL
54        GOBIERNO ONAL
55       GERNO REGIONAL
Name: inst1, dtype: object

In [94]:
# ussando map 

data['inst1'] = data['institución_ruc'].map(lambda x: re.sub('[0-9]','',x))
data['inst1']

0       GOBIERNO REONAL
1                  MINS
2     GOBIERNO REGIONAL
3                  MNSA
4          GOBIERNO REG
5     GOBIERNO REGIONAL
6         GOBIER EGIOAL
7     GOBIERNO REGIONAL
8       GOBIERNO GIONAL
9     GOBIERNO REGIONAL
10                MINSA
11                MINSA
12    GOBIERNO REGIONAL
13    GOBIERNO REGIONAL
14    GOBIERNO REGIONAL
15    GOBIERNO REGIONAL
16    GOBIERNO REGIONAL
17                MINzA
18    GOBIERNO REGIONAL
19    GOBIERNO REGIONAL
20    GOBIERNO REGIONAL
21    GOBIERNO REGIONAL
22    GOBIERNO REGIONAL
23    GOBIERNO REGIONAL
24    GOBIERNO REGIONAL
25    GOBIERNO REGIONAL
26    GOBIERNO REGIONAL
27    GOBIERNO REGIONAL
28                MINSA
29    GOBIERNO REGIONAL
30    GOBIERNO REGIONAL
31             REGIONAL
32    GOBIERNO REGIONAL
33    GOBIERNO REGIONAL
34    GOBIERNO REGIONAL
35                  MIA
36    GOBIERNO REGIONAL
37    GOBIERNO REGIONAL
38    GOBIERNO REGIONAL
39        GOBIER GIONAL
40    GOBIERNO REGIONAL
41    GOBIERNO REGIONAL
42         GOBIEEGIONAL
43    GOBIERNO REGIONAL
44    GOBIERNO REGIONAL
45                  MSA
46    GOBIERNO REGIONAL
47             REGIONAL
48    GOBIERNO REGIONAL
49           GOBIERONAL
50    GOBIERNO REGIONAL
51    GOBIERNO REGIONAL
52                MINSA
53    GOBIERNO REGIONAL
54        GOBIERNO ONAL
55       GERNO REGIONAL
Name: inst1, dtype: object

In [104]:
regex = re.compile('[0-9]') # establecemos el patron. Es este caso, detectar todos los numeros

data['inst2'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['inst2']

0       GOBIERNO REONAL
1                  MINS
2     GOBIERNO REGIONAL
3                  MNSA
4          GOBIERNO REG
5     GOBIERNO REGIONAL
6         GOBIER EGIOAL
7     GOBIERNO REGIONAL
8       GOBIERNO GIONAL
9     GOBIERNO REGIONAL
10                MINSA
11                MINSA
12    GOBIERNO REGIONAL
13    GOBIERNO REGIONAL
14    GOBIERNO REGIONAL
15    GOBIERNO REGIONAL
16    GOBIERNO REGIONAL
17                MINzA
18    GOBIERNO REGIONAL
19    GOBIERNO REGIONAL
20    GOBIERNO REGIONAL
21    GOBIERNO REGIONAL
22    GOBIERNO REGIONAL
23    GOBIERNO REGIONAL
24    GOBIERNO REGIONAL
25    GOBIERNO REGIONAL
26    GOBIERNO REGIONAL
27    GOBIERNO REGIONAL
28                MINSA
29    GOBIERNO REGIONAL
30    GOBIERNO REGIONAL
31             REGIONAL
32    GOBIERNO REGIONAL
33    GOBIERNO REGIONAL
34    GOBIERNO REGIONAL
35                  MIA
36    GOBIERNO REGIONAL
37    GOBIERNO REGIONAL
38    GOBIERNO REGIONAL
39        GOBIER GIONAL
40    GOBIERNO REGIONAL
41    GOBIERNO REGIONAL
42         GOBIEEGIONAL
43    GOBIERNO REGIONAL
44    GOBIERNO REGIONAL
45                  MSA
46    GOBIERNO REGIONAL
47             REGIONAL
48    GOBIERNO REGIONAL
49           GOBIERONAL
50    GOBIERNO REGIONAL
51    GOBIERNO REGIONAL
52                MINSA
53    GOBIERNO REGIONAL
54        GOBIERNO ONAL
55       GERNO REGIONAL
Name: inst2, dtype: object

In [96]:
# Alternativas 1

# usando \d <> [0-9] 

regex = re.compile('\d')

data['inst2'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['inst2']

0       GOBIERNO REONAL
1                  MINS
2     GOBIERNO REGIONAL
3                  MNSA
4          GOBIERNO REG
5     GOBIERNO REGIONAL
6         GOBIER EGIOAL
7     GOBIERNO REGIONAL
8       GOBIERNO GIONAL
9     GOBIERNO REGIONAL
10                MINSA
11                MINSA
12    GOBIERNO REGIONAL
13    GOBIERNO REGIONAL
14    GOBIERNO REGIONAL
15    GOBIERNO REGIONAL
16    GOBIERNO REGIONAL
17                MINzA
18    GOBIERNO REGIONAL
19    GOBIERNO REGIONAL
20    GOBIERNO REGIONAL
21    GOBIERNO REGIONAL
22    GOBIERNO REGIONAL
23    GOBIERNO REGIONAL
24    GOBIERNO REGIONAL
25    GOBIERNO REGIONAL
26    GOBIERNO REGIONAL
27    GOBIERNO REGIONAL
28                MINSA
29    GOBIERNO REGIONAL
30    GOBIERNO REGIONAL
31             REGIONAL
32    GOBIERNO REGIONAL
33    GOBIERNO REGIONAL
34    GOBIERNO REGIONAL
35                  MIA
36    GOBIERNO REGIONAL
37    GOBIERNO REGIONAL
38    GOBIERNO REGIONAL
39        GOBIER GIONAL
40    GOBIERNO REGIONAL
41    GOBIERNO REGIONAL
42         GOBIEEGIONAL
43    GOBIERNO REGIONAL
44    GOBIERNO REGIONAL
45                  MSA
46    GOBIERNO REGIONAL
47             REGIONAL
48    GOBIERNO REGIONAL
49           GOBIERONAL
50    GOBIERNO REGIONAL
51    GOBIERNO REGIONAL
52                MINSA
53    GOBIERNO REGIONAL
54        GOBIERNO ONAL
55       GERNO REGIONAL
Name: inst2, dtype: object

In [102]:
# Alternativas 2
regex = re.compile('[^a-zA-Z\s]') # distitnto a letras y espacio, se reemplaza por el vacío

data['inst3'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['inst3']

0       GOBIERNO REONAL
1                  MINS
2     GOBIERNO REGIONAL
3                  MNSA
4          GOBIERNO REG
5     GOBIERNO REGIONAL
6         GOBIER EGIOAL
7     GOBIERNO REGIONAL
8       GOBIERNO GIONAL
9     GOBIERNO REGIONAL
10                MINSA
11                MINSA
12    GOBIERNO REGIONAL
13    GOBIERNO REGIONAL
14    GOBIERNO REGIONAL
15    GOBIERNO REGIONAL
16    GOBIERNO REGIONAL
17                MINzA
18    GOBIERNO REGIONAL
19    GOBIERNO REGIONAL
20    GOBIERNO REGIONAL
21    GOBIERNO REGIONAL
22    GOBIERNO REGIONAL
23    GOBIERNO REGIONAL
24    GOBIERNO REGIONAL
25    GOBIERNO REGIONAL
26    GOBIERNO REGIONAL
27    GOBIERNO REGIONAL
28                MINSA
29    GOBIERNO REGIONAL
30    GOBIERNO REGIONAL
31             REGIONAL
32    GOBIERNO REGIONAL
33    GOBIERNO REGIONAL
34    GOBIERNO REGIONAL
35                  MIA
36    GOBIERNO REGIONAL
37    GOBIERNO REGIONAL
38    GOBIERNO REGIONAL
39        GOBIER GIONAL
40    GOBIERNO REGIONAL
41    GOBIERNO REGIONAL
42         GOBIEEGIONAL
43    GOBIERNO REGIONAL
44    GOBIERNO REGIONAL
45                  MSA
46    GOBIERNO REGIONAL
47             REGIONAL
48    GOBIERNO REGIONAL
49           GOBIERONAL
50    GOBIERNO REGIONAL
51    GOBIERNO REGIONAL
52                MINSA
53    GOBIERNO REGIONAL
54        GOBIERNO ONAL
55       GERNO REGIONAL
Name: inst3, dtype: object

In [86]:
# Limpiar los caracteres extras del siquiente nombre 

nombre = "JOAN ANDREU CRUZ / # . --+"

regex = re.compile("")
regex.sub('', nombre)

## "2.0 extraccción de numeros"

In [296]:
# Alternativas 1

regex = re.compile('[a-zA-Z]') # patron es detectar letras minusculas o mayusculas

data['ruc1'] = data['institución_ruc'].apply(lambda x: regex.sub('',x).strip())
data['ruc1'] = data['ruc1'].replace('', np.nan).astype('Int64')

In [302]:
#Alternativa

data['ruc1'] = data['institución_ruc'].apply(lambda x: int(regex.sub('',x).strip()) if  regex.sub('',x).strip().isdigit() else np.nan)

In [303]:
data[['ruc1']]

            ruc1
0   2.014791e+10
1   2.060222e+10
2   2.017266e+10
3   2.060222e+10
4   2.021891e+10
5   2.021891e+10
6   2.021891e+10
7   2.021891e+10
8   2.019992e+10
9            NaN
10  2.060225e+10
11  2.060225e+10
12  2.017266e+10
13  2.049022e+10
14  2.045074e+10
15  2.014569e+10
16  2.022231e+10
17  2.060222e+10
18  2.019957e+10
19  2.017026e+10
20  2.017100e+10
21  2.016565e+10
22  2.048925e+10
23  2.060280e+10
24  2.017266e+10
25  2.060398e+10
26  2.019105e+10
27  2.049022e+10
28  2.060225e+10
29  2.017026e+10
30  2.045024e+10
31  2.017118e+10
32  2.016383e+10
33  2.015600e+10
34           NaN
35  2.060225e+10
36  2.049124e+10
37  2.053132e+10
38  2.016724e+10
39  2.014569e+10
40  2.014569e+10
41  2.014569e+10
42  2.015618e+10
43  2.045231e+10
44  2.048639e+10
45  2.060225e+10
46  2.017266e+10
47  2.017100e+10
48  2.041104e+10
49  2.017118e+10
50  2.016220e+10
51  2.060099e+10
52  2.060224e+10
53  2.053479e+10
54  2.052844e+10
55  2.036384e+10

In [174]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   departamento     56 non-null     object
 1   provincia        56 non-null     object
 2   distrito         56 non-null     object
 3   ubigeo_string    56 non-null     int64
 4   ubigeo_numero    56 non-null     int64
 5   dirección        56 non-null     object
 6   institución_ruc  56 non-null     object
 7   fecha_apertura   56 non-null     object
 8   gps              52 non-null     object
 9   resolucion       56 non-null     object
 10  telefono         53 non-null     object
 11  horario          56 non-null     object
 12  presupuesto      56 non-null     object
 13  inst1            56 non-null     object
 14  inst2            56 non-null     object
 15  inst3            56 non-null     object
 16  ruc1             54 non-null     float64
 17  ruc2             56 non-null     object
 18  ruc3             56 non-null     object
 19  ruc4             56 non-null     object
 20  fecha_apertura1  56 non-null     object
 21  coordinates2     56 non-null     object
 22  coordinates3     56 non-null     object
 23  coordinates4     56 non-null     object
dtypes: float64(1), int64(2), object(21)
memory usage: 10.6+ KB

In [120]:
# Alternativas 2
regex = re.compile('[a-zA-Z\s]')

data['ruc2'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['ruc2']

0     20147907487
1     20602217508
2     20172661794
3     20602217508
4     20218911189
5     20218911189
6     20218911189
7     20218911189
8     20199917928
9
10    20602251641
11    20602250602
12    20172661794
13    20490215850
14    20450736539
15    20145686548
16    20222308080
17    20602217508
18    20199565398
19    20170258054
20    20171001065
21    20165645325
22    20489252601
23    20602799973
24    20172661794
25    20603980248
26    20191045671
27    20490215850
28    20602250602
29    20170258054
30    20450241564
31    20171178585
32    20163833094
33    20156003817
34
35    20602251641
36    20491240742
37    20531320574
38    20167237895
39    20145686548
40    20145686548
41    20145686548
42    20156176240
43    20452308992
44    20486391279
45    20602250602
46    20172661794
47    20171001065
48    20411038506
49    20171178585
50    20162197461
51    20600985206
52    20602236596
53    20534791381
54    20528442154
55    20363839500
Name: ruc2, dtype: object

In [121]:
# Alternativas 3
regex = re.compile('\D') # Todo lo que sea distinto a digitos 

data['ruc3'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['ruc3']

#\D: caracteres diferetnes de digitos

0     20147907487
1     20602217508
2     20172661794
3     20602217508
4     20218911189
5     20218911189
6     20218911189
7     20218911189
8     20199917928
9
10    20602251641
11    20602250602
12    20172661794
13    20490215850
14    20450736539
15    20145686548
16    20222308080
17    20602217508
18    20199565398
19    20170258054
20    20171001065
21    20165645325
22    20489252601
23    20602799973
24    20172661794
25    20603980248
26    20191045671
27    20490215850
28    20602250602
29    20170258054
30    20450241564
31    20171178585
32    20163833094
33    20156003817
34
35    20602251641
36    20491240742
37    20531320574
38    20167237895
39    20145686548
40    20145686548
41    20145686548
42    20156176240
43    20452308992
44    20486391279
45    20602250602
46    20172661794
47    20171001065
48    20411038506
49    20171178585
50    20162197461
51    20600985206
52    20602236596
53    20534791381
54    20528442154
55    20363839500
Name: ruc3, dtype: object

In [126]:
# Alternativas 4


 # Son equivalentes \D <> [^0-9]
    
regex = re.compile('[^0-9]')

data['ruc4'] = data['institución_ruc'].apply(lambda x: regex.sub('',x))
data['ruc4']

0     20147907487
1     20602217508
2     20172661794
3     20602217508
4     20218911189
5     20218911189
6     20218911189
7     20218911189
8     20199917928
9
10    20602251641
11    20602250602
12    20172661794
13    20490215850
14    20450736539
15    20145686548
16    20222308080
17    20602217508
18    20199565398
19    20170258054
20    20171001065
21    20165645325
22    20489252601
23    20602799973
24    20172661794
25    20603980248
26    20191045671
27    20490215850
28    20602250602
29    20170258054
30    20450241564
31    20171178585
32    20163833094
33    20156003817
34
35    20602251641
36    20491240742
37    20531320574
38    20167237895
39    20145686548
40    20145686548
41    20145686548
42    20156176240
43    20452308992
44    20486391279
45    20602250602
46    20172661794
47    20171001065
48    20411038506
49    20171178585
50    20162197461
51    20600985206
52    20602236596
53    20534791381
54    20528442154
55    20363839500
Name: ruc4, dtype: object

In [127]:
data['fecha_apertura']

0         28/06/15 :00:00
1              01/10/2015
2                00/00/00
3              10/07/2018
4              28/08/2018
5              02/11/2018
6              31/12/2018
7       01/07/19   :00:00
8              01/10/2019
9              10/10/2019
10             05/11/2019
11             15/11/2019
12               00/00/00
13             15/12/2019
14             26/06/2020
15             01/10/2020
16             01/10/2020
17       02/11/20  :00:00
18             02/11/2020
19             03/11/2020
20         04/11/2020 !%&
21             04/11/2020
22             11/11/2020
23               00/00/00
24             13/11/2020
25             14/11/2020
26             15/11/2020
27             19/11/2020
28             01/12/2020
29        15/06/21 :00:00
30             29/06/2021
31             08/08/2021
32               00/00/00
33             12/11/2021
34             01/01/2019
35             01/02/2021
36             03/01/2020
37             01/04/2019
38      01/06/15   :00:00
39             01/06/2015
40             01/06/2015
41             01/06/2015
42             01/06/2018
43             01/06/2021
44        01/07/17    !%&
45             01/07/2018
46             01/08/2015
47             01/08/2018
48             01/08/2018
49               00/00/00
50             01/08/2018
51             01/08/2019
52             01/09/2018
53     01/10/2018  :00:00
54             01/10/2019
55    01/10/2019   :00:00
Name: fecha_apertura, dtype: object

In [129]:
# Sustituir caracteres diferentes a la fecha
regex = re.compile(':00:00|!%&|00/00/00')

data['fecha_apertura1'] = data['fecha_apertura'].apply(lambda x: regex.sub('',x).strip())
data['fecha_apertura1']

0       28/06/15
1     01/10/2015
2
3     10/07/2018
4     28/08/2018
5     02/11/2018
6     31/12/2018
7       01/07/19
8     01/10/2019
9     10/10/2019
10    05/11/2019
11    15/11/2019
12
13    15/12/2019
14    26/06/2020
15    01/10/2020
16    01/10/2020
17      02/11/20
18    02/11/2020
19    03/11/2020
20    04/11/2020
21    04/11/2020
22    11/11/2020
23
24    13/11/2020
25    14/11/2020
26    15/11/2020
27    19/11/2020
28    01/12/2020
29      15/06/21
30    29/06/2021
31    08/08/2021
32
33    12/11/2021
34    01/01/2019
35    01/02/2021
36    03/01/2020
37    01/04/2019
38      01/06/15
39    01/06/2015
40    01/06/2015
41    01/06/2015
42    01/06/2018
43    01/06/2021
44      01/07/17
45    01/07/2018
46    01/08/2015
47    01/08/2018
48    01/08/2018
49
50    01/08/2018
51    01/08/2019
52    01/09/2018
53    01/10/2018
54    01/10/2019
55    01/10/2019
Name: fecha_apertura1, dtype: object

In [ ]:
# Extraer la edad

dato = "El criminal dice tener 28 años"

# re.findall

- Econtrar una estructura o patron en el texto

In [141]:
data['gps']

0        @-12.14,-74.561!ayay%6
1         @-12.14,-74.56!ayay%7
2      @-12.151,-74.5615!ayay%8
3         @-12.14,-74.12!ayay%9
4       @-12.1,-74.5615!ayay%10
5     @-12.140,-74.5615!ayay%11
6      @-12.14,-74.5615!ayay%12
7        @-12.13,-74.69!ayay%13
8      @-12.14,-74.5615!ayay%14
9      @-12.14,-74.5615!ayay%15
10     @-12.14,-74.5615!ayay%16
11     @-12.14,-74.5615!ayay%17
12     @-12.14,-74.5615!ayay%18
13     @-12.14,-74.5615!ayay%19
14     @-12.14,-74.5615!ayay%20
15     @-12.14,-74.5615!ayay%21
16                          NaN
17     @-12.14,-74.5615!ayay%23
18     @-12.14,-74.5615!ayay%24
19     @-12.14,-74.5615!ayay%25
20     @-12.14,-74.5615!ayay%26
21        @-12.14,-74.3!ayay%27
22     @-12.14,-74.5615!ayay%28
23     @-12.14,-74.5615!ayay%29
24     @-12.14,-74.5615!ayay%30
25     @-12.14,-74.5615!ayay%31
26     @-12.14,-74.5615!ayay%32
27     @-12.14,-74.5615!ayay%33
28     @-12.16,-74.5615!ayay%34
29                          NaN
30     @-12.14,-74.5615!ayay%36
31     @-12.14,-74.5615!ayay%37
32     @-12.19,-74.5615!ayay%38
33     @-12.14,-74.5615!ayay%39
34     @-12.14,-74.5615!ayay%40
35     @-12.14,-74.5615!ayay%41
36     @-12.14,-74.5615!ayay%42
37                          NaN
38     @-12.14,-73.5615!ayay%44
39     @-12.14,-74.5615!ayay%45
40     @-12.14,-74.5615!ayay%46
41     @-12.14,-74.5615!ayay%47
42     @-12.14,-74.5615!ayay%48
43        @-12.14,-74.9!ayay%49
44     @-12.14,-74.5615!ayay%50
45     @-12.14,-74.5615!ayay%51
46                          NaN
47     @-12.14,-74.5615!ayay%53
48     @-12.14,-74.5615!ayay%54
49     @-12.14,-74.5615!ayay%55
50     @-12.14,-74.5615!ayay%56
51     @-12.14,-74.5615!ayay%57
52     @-12.14,-74.5615!ayay%58
53     @-12.14,-74.5615!ayay%59
54     @-12.14,-74.5615!ayay%60
55     @-12.14,-74.5115!ayay%61
Name: gps, dtype: object

In [281]:
# re.findall requiere un formato espefico del texto a extreaer

# -12.14,-74.5115 (longitud, latitud)

regex = re.compile('-\d+.\d+,-\d+.\d+')

data['coordinates1'] = data['gps'].apply(lambda x: regex.findall(str(x)) )
data['coordinates1']

0       [-12.14,-74.561]
1        [-12.14,-74.56]
2     [-12.151,-74.5615]
3        [-12.14,-74.12]
4       [-12.1,-74.5615]
5     [-12.140,-74.5615]
6      [-12.14,-74.5615]
7        [-12.13,-74.69]
8      [-12.14,-74.5615]
9      [-12.14,-74.5615]
10     [-12.14,-74.5615]
11     [-12.14,-74.5615]
12     [-12.14,-74.5615]
13     [-12.14,-74.5615]
14     [-12.14,-74.5615]
15     [-12.14,-74.5615]
16                    []
17     [-12.14,-74.5615]
18     [-12.14,-74.5615]
19     [-12.14,-74.5615]
20     [-12.14,-74.5615]
21        [-12.14,-74.3]
22     [-12.14,-74.5615]
23     [-12.14,-74.5615]
24     [-12.14,-74.5615]
25     [-12.14,-74.5615]
26     [-12.14,-74.5615]
27     [-12.14,-74.5615]
28     [-12.16,-74.5615]
29                    []
30     [-12.14,-74.5615]
31     [-12.14,-74.5615]
32     [-12.19,-74.5615]
33     [-12.14,-74.5615]
34     [-12.14,-74.5615]
35     [-12.14,-74.5615]
36     [-12.14,-74.5615]
37                    []
38     [-12.14,-73.5615]
39     [-12.14,-74.5615]
40     [-12.14,-74.5615]
41     [-12.14,-74.5615]
42     [-12.14,-74.5615]
43        [-12.14,-74.9]
44     [-12.14,-74.5615]
45     [-12.14,-74.5615]
46                    []
47     [-12.14,-74.5615]
48     [-12.14,-74.5615]
49     [-12.14,-74.5615]
50     [-12.14,-74.5615]
51     [-12.14,-74.5615]
52     [-12.14,-74.5615]
53     [-12.14,-74.5615]
54     [-12.14,-74.5615]
55     [-12.14,-74.5115]
Name: coordinates1, dtype: object

In [274]:
regex = re.compile('-\d+.\d+,-\d+.\d+')

data['gps'].apply(lambda x: regex.findall( str(x)) )

0       [-12.14,-74.561]
1        [-12.14,-74.56]
2     [-12.151,-74.5615]
3        [-12.14,-74.12]
4       [-12.1,-74.5615]
5     [-12.140,-74.5615]
6      [-12.14,-74.5615]
7        [-12.13,-74.69]
8      [-12.14,-74.5615]
9      [-12.14,-74.5615]
10     [-12.14,-74.5615]
11     [-12.14,-74.5615]
12     [-12.14,-74.5615]
13     [-12.14,-74.5615]
14     [-12.14,-74.5615]
15     [-12.14,-74.5615]
16                    []
17     [-12.14,-74.5615]
18     [-12.14,-74.5615]
19     [-12.14,-74.5615]
20     [-12.14,-74.5615]
21        [-12.14,-74.3]
22     [-12.14,-74.5615]
23     [-12.14,-74.5615]
24     [-12.14,-74.5615]
25     [-12.14,-74.5615]
26     [-12.14,-74.5615]
27     [-12.14,-74.5615]
28     [-12.16,-74.5615]
29                    []
30     [-12.14,-74.5615]
31     [-12.14,-74.5615]
32     [-12.19,-74.5615]
33     [-12.14,-74.5615]
34     [-12.14,-74.5615]
35     [-12.14,-74.5615]
36     [-12.14,-74.5615]
37                    []
38     [-12.14,-73.5615]
39     [-12.14,-74.5615]
40     [-12.14,-74.5615]
41     [-12.14,-74.5615]
42     [-12.14,-74.5615]
43        [-12.14,-74.9]
44     [-12.14,-74.5615]
45     [-12.14,-74.5615]
46                    []
47     [-12.14,-74.5615]
48     [-12.14,-74.5615]
49     [-12.14,-74.5615]
50     [-12.14,-74.5615]
51     [-12.14,-74.5615]
52     [-12.14,-74.5615]
53     [-12.14,-74.5615]
54     [-12.14,-74.5615]
55     [-12.14,-74.5115]
Name: gps, dtype: object

In [143]:
#Se obtiene error pues la variable gps celdas nan que son float y no string

regex = re.compile('-\d+.\d+,-\d+.\d+')

data['coordinates2'] = data['gps'].apply(lambda x: regex.findall( str(x)  ) )
data['coordinates2']

0       [-12.14,-74.561]
1        [-12.14,-74.56]
2     [-12.151,-74.5615]
3        [-12.14,-74.12]
4       [-12.1,-74.5615]
5     [-12.140,-74.5615]
6      [-12.14,-74.5615]
7        [-12.13,-74.69]
8      [-12.14,-74.5615]
9      [-12.14,-74.5615]
10     [-12.14,-74.5615]
11     [-12.14,-74.5615]
12     [-12.14,-74.5615]
13     [-12.14,-74.5615]
14     [-12.14,-74.5615]
15     [-12.14,-74.5615]
16                    []
17     [-12.14,-74.5615]
18     [-12.14,-74.5615]
19     [-12.14,-74.5615]
20     [-12.14,-74.5615]
21        [-12.14,-74.3]
22     [-12.14,-74.5615]
23     [-12.14,-74.5615]
24     [-12.14,-74.5615]
25     [-12.14,-74.5615]
26     [-12.14,-74.5615]
27     [-12.14,-74.5615]
28     [-12.16,-74.5615]
29                    []
30     [-12.14,-74.5615]
31     [-12.14,-74.5615]
32     [-12.19,-74.5615]
33     [-12.14,-74.5615]
34     [-12.14,-74.5615]
35     [-12.14,-74.5615]
36     [-12.14,-74.5615]
37                    []
38     [-12.14,-73.5615]
39     [-12.14,-74.5615]
40     [-12.14,-74.5615]
41     [-12.14,-74.5615]
42     [-12.14,-74.5615]
43        [-12.14,-74.9]
44     [-12.14,-74.5615]
45     [-12.14,-74.5615]
46                    []
47     [-12.14,-74.5615]
48     [-12.14,-74.5615]
49     [-12.14,-74.5615]
50     [-12.14,-74.5615]
51     [-12.14,-74.5615]
52     [-12.14,-74.5615]
53     [-12.14,-74.5615]
54     [-12.14,-74.5615]
55     [-12.14,-74.5115]
Name: coordinates2, dtype: object

In [146]:
# se captura la presencia de más de un digito \d+, str(x): transforma a texto cada fila de la columna 

regex = re.compile('-\d{1,2}.\d{1,3},-\d{2}.\d{1,2}')

# \d{1,3}: extrae entre 1 a 3 digitos

data['coordinates3'] = data['gps'].apply(lambda x: regex.findall( str(x)  ))
data['coordinates3']

0      [-12.14,-74.56]
1      [-12.14,-74.56]
2     [-12.151,-74.56]
3      [-12.14,-74.12]
4       [-12.1,-74.56]
5     [-12.140,-74.56]
6      [-12.14,-74.56]
7      [-12.13,-74.69]
8      [-12.14,-74.56]
9      [-12.14,-74.56]
10     [-12.14,-74.56]
11     [-12.14,-74.56]
12     [-12.14,-74.56]
13     [-12.14,-74.56]
14     [-12.14,-74.56]
15     [-12.14,-74.56]
16                  []
17     [-12.14,-74.56]
18     [-12.14,-74.56]
19     [-12.14,-74.56]
20     [-12.14,-74.56]
21      [-12.14,-74.3]
22     [-12.14,-74.56]
23     [-12.14,-74.56]
24     [-12.14,-74.56]
25     [-12.14,-74.56]
26     [-12.14,-74.56]
27     [-12.14,-74.56]
28     [-12.16,-74.56]
29                  []
30     [-12.14,-74.56]
31     [-12.14,-74.56]
32     [-12.19,-74.56]
33     [-12.14,-74.56]
34     [-12.14,-74.56]
35     [-12.14,-74.56]
36     [-12.14,-74.56]
37                  []
38     [-12.14,-73.56]
39     [-12.14,-74.56]
40     [-12.14,-74.56]
41     [-12.14,-74.56]
42     [-12.14,-74.56]
43      [-12.14,-74.9]
44     [-12.14,-74.56]
45     [-12.14,-74.56]
46                  []
47     [-12.14,-74.56]
48     [-12.14,-74.56]
49     [-12.14,-74.56]
50     [-12.14,-74.56]
51     [-12.14,-74.56]
52     [-12.14,-74.56]
53     [-12.14,-74.56]
54     [-12.14,-74.56]
55     [-12.14,-74.51]
Name: coordinates3, dtype: object

In [288]:
# Columnas separadas para longitud y latitud

regex_gps = re.compile('-\d+.\d+,-\d+.\d+')

data[['long','lat']] = data['gps'].apply(lambda x:  ''.join( regex_gps.findall( str(x) ) ) ).str.split(",", expand = True)
data[['long','lat']]

       long       lat
0    -12.14   -74.561
1    -12.14    -74.56
2   -12.151  -74.5615
3    -12.14    -74.12
4     -12.1  -74.5615
5   -12.140  -74.5615
6    -12.14  -74.5615
7    -12.13    -74.69
8    -12.14  -74.5615
9    -12.14  -74.5615
10   -12.14  -74.5615
11   -12.14  -74.5615
12   -12.14  -74.5615
13   -12.14  -74.5615
14   -12.14  -74.5615
15   -12.14  -74.5615
16               None
17   -12.14  -74.5615
18   -12.14  -74.5615
19   -12.14  -74.5615
20   -12.14  -74.5615
21   -12.14     -74.3
22   -12.14  -74.5615
23   -12.14  -74.5615
24   -12.14  -74.5615
25   -12.14  -74.5615
26   -12.14  -74.5615
27   -12.14  -74.5615
28   -12.16  -74.5615
29               None
30   -12.14  -74.5615
31   -12.14  -74.5615
32   -12.19  -74.5615
33   -12.14  -74.5615
34   -12.14  -74.5615
35   -12.14  -74.5615
36   -12.14  -74.5615
37               None
38   -12.14  -73.5615
39   -12.14  -74.5615
40   -12.14  -74.5615
41   -12.14  -74.5615
42   -12.14  -74.5615
43   -12.14     -74.9
44   -12.14  -74.5615
45   -12.14  -74.5615
46               None
47   -12.14  -74.5615
48   -12.14  -74.5615
49   -12.14  -74.5615
50   -12.14  -74.5615
51   -12.14  -74.5615
52   -12.14  -74.5615
53   -12.14  -74.5615
54   -12.14  -74.5615
55   -12.14  -74.5115

# re.search

- Busqueda de patrones para extraer de un texto

In [34]:
# extracción del nombre de distrito y región 


x = "AVENIDA LA PAZ CUADRA 3 LA PERLA CALLAO CALLAO distrito LA PERLA Region El CALLAO"

print(re.search('[D/d]istrito ([\w+\-\s]+) [R/r]egion ([\w+\s]+)', x).group(1))

re.search('[D/d]istrito ([\w+\-\s]+) [R/r]egion ([\w+\s]+)', x).group(2)

LA PERLA

'El CALLAO'

In [35]:
# () permite capturar lo que me interesa. Puede acceder a cada grupo de interés mediante .group()

In [36]:

def dist_region(x):
    regex_area = re.compile('[D/d]istrito ([\w+\-\s]*) [R/r]egion ([\w+\s]*)')
    output =  regex_area.search(x)
    
    return output.group(1), output.group(2)
 
     
data['distrito'] = data['dirección'].apply(lambda x: dist_region(x)[0])
data['distrito']

0                          LA PERLA
1                             RIMAC
2     JOSE LUIS BUSTAMANTE Y RIVERO
3                             COMAS
4                       EL PORVENIR
5                 FLORENCIA DE MORA
6                       EL PORVENIR
7                          TRUJILLO
8                          TALAVERA
9                             NAUTA
10                VILLA EL SALVADOR
11                      LA VICTORIA
12                            APLAO
13                            CALCA
14                    SAN SEBASTIAN
15                          JULIACA
16                       HUAMACHUCO
17                       LOS OLIVOS
18                            PAITA
19                        TAMBOPATA
20                           TUMBES
21                          CUTERVO
22                        RUPA-RUPA
23                            PANAO
24                            MAJES
25                        CAJAMARCA
26                         OXAPAMPA
27                         SANTIAGO
28                             LIMA
29                         INAMBARI
30                       YURIMAGUAS
31                            SALAS
32                           ILLIMO
33                    INDEPENDENCIA
34                         IMPERIAL
35                       CHORRILLOS
36                        CURAHUASI
37                          TOCACHE
38                           CAMANA
39                          JULIACA
40                          JULIACA
41                       SAN MIGUEL
42                         LA OROYA
43                   LOS MOROCHUCOS
44                           CHILCA
45                     PUEBLO LIBRE
46                       COCACHACRA
47                        ZARUMILLA
48                            CHOTA
49                     VISTA ALEGRE
50                           HUACHO
51                     HUANCAVELICA
52                      SANTA ANITA
53                            PALPA
54                         BARRANCA
55                         HUANCANE
Name: distrito, dtype: object

In [37]:
data['region'] = data['dirección'].apply(lambda x: dist_region(x)[1])
data['region']

0            CALLAO
1              LIMA
2          AREQUIPA
3              LIMA
4       LA LIBERTAD
5       LA LIBERTAD
6       LA LIBERTAD
7       LA LIBERTAD
8          APURIMAC
9            LORETO
10             LIMA
11             LIMA
12         AREQUIPA
13            CUSCO
14            CUSCO
15             PUNO
16      LA LIBERTAD
17             LIMA
18            PIURA
19    MADRE DE DIOS
20           TUMBES
21        CAJAMARCA
22          HUANUCO
23          HUANUCO
24         AREQUIPA
25        CAJAMARCA
26            PASCO
27            CUSCO
28             LIMA
29    MADRE DE DIOS
30           LORETO
31              ICA
32       LAMBAYEQUE
33           ANCASH
34             LIMA
35             LIMA
36         APURIMAC
37       SAN MARTIN
38         AREQUIPA
39             PUNO
40             PUNO
41             PUNO
42            JUNIN
43         AYACUCHO
44            JUNIN
45             LIMA
46         AREQUIPA
47           TUMBES
48        CAJAMARCA
49              ICA
50             LIMA
51     HUANCAVELICA
52             LIMA
53              ICA
54           LORETO
55             PUNO
Name: region, dtype: object

In [38]:
#Extracción del número telefónico

data['telefono']

0     telf: 145-36985
1     telf: 145-36986
2     telf: 145-36987
3          telf: 45-3
4     telf: 145-36989
5     telf: 145-36990
6                 NaN
7     telf: 145-36992
8     telf: 145-36993
9     telf: 145-36994
10    telf: 145-36995
11    telf: 145-36996
12    telf: 145-36997
13    telf: 145-36998
14    telf: 145-36999
15    telf: 145-37000
16    telf: 145-37001
17    telf: 145-37002
18             telf:
19    telf: 145-37004
20    telf: 145-37005
21    telf: 145-37006
22    telf: 145-37007
23    telf: 145-37008
24    telf: 145-37009
25    telf: 145-37010
26    telf: 145-37011
27    telf: 145-37012
28                NaN
29    telf: 145-37014
30    telf: 145-37015
31    telf: 145-37016
32    telf: 145-37017
33    telf: 145-37018
34    telf: 145-37019
35    telf: 145-37020
36    telf: 145-37021
37    telf: 145-37022
38    telf: 145-37023
39    telf: 145-37024
40             telf:
41    telf: 145-37026
42    telf: 145-37027
43    telf: 145-37028
44    telf: 145-37029
45    telf: 145-37030
46    telf: 145-37031
47    telf: 145-37032
48    telf: 145-37033
49             telf:
50    telf: 145-37035
51    telf: 145-37036
52    telf: 145-37037
53                NaN
54    telf: 145-37039
55    telf: 145-37040
Name: telefono, dtype: object

In [39]:
def phone(x):
    
    try:
        match_regex = re.compile('(\d+\-\d+)')
        match = match_regex.search(str(x))
    
        return match.group(1)
    
    # Si no encuentra un grupo por precencia de missing, se ejecuta la siguiente linea
    
    except:
        
        None

In [40]:
data['phone'] = data['telefono'].apply(lambda x: phone(x))
data['phone']

0     145-36985
1     145-36986
2     145-36987
3          45-3
4     145-36989
5     145-36990
6          None
7     145-36992
8     145-36993
9     145-36994
10    145-36995
11    145-36996
12    145-36997
13    145-36998
14    145-36999
15    145-37000
16    145-37001
17    145-37002
18         None
19    145-37004
20    145-37005
21    145-37006
22    145-37007
23    145-37008
24    145-37009
25    145-37010
26    145-37011
27    145-37012
28         None
29    145-37014
30    145-37015
31    145-37016
32    145-37017
33    145-37018
34    145-37019
35    145-37020
36    145-37021
37    145-37022
38    145-37023
39    145-37024
40         None
41    145-37026
42    145-37027
43    145-37028
44    145-37029
45    145-37030
46    145-37031
47    145-37032
48    145-37033
49         None
50    145-37035
51    145-37036
52    145-37037
53         None
54    145-37039
55    145-37040
Name: phone, dtype: object

In [41]:
# Resolución
data['resolucion']

0       DS-023-2015 PCM
1       DS-024-2015 PCM
2     DS-012-2014 MINSA
3       DS-026-2016 PCM
4     DS-023-2015 MINSA
5       DS-027-2015 PCM
6       DS-028-2015 PCM
7     DS-029-2016 MINSA
8       DS-030-2014 PCM
9       DS-024-2012 PCM
10      DS-030-2015 PCM
11      DS-031-2015 PCM
12      DS-032-2015 PCM
13    DS-033-2015 MINSA
14      DS-034-2015 PCM
15      DS-035-2015 PCM
16      DS-036-2015 PCM
17      DS-037-2015 PCM
18      DS-038-2015 PCM
19    DS-039-2015 MINSA
20      DS-040-2015 PCM
21    DS-041-2015 MINSA
22      DS-042-2015 PCM
23    DS-043-2015 MINSA
24      DS-044-2015 PCM
25      DS-045-2015 PCM
26      DS-046-2015 PCM
27    DS-047-2015 MINSA
28      DS-048-2015 PCM
29      DS-049-2015 PCM
30    DS-050-2015 MINSA
31      DS-051-2015 PCM
32      DS-052-2015 PCM
33      DS-053-2015 PCM
34      DS-054-2015 PCM
35      DS-055-2015 PCM
36      DS-056-2015 PCM
37    DS-057-2015 MINSA
38      DS-058-2015 PCM
39      DS-059-2015 PCM
40    DS-060-2015 MINSA
41      DS-062-2015 PCM
42      DS-063-2015 PCM
43    DS-064-2015 MINSA
44      DS-065-2015 PCM
45       DS-06-2015 PCM
46      DS-067-2015 PCM
47      DS-068-2015 PCM
48      DS-069-2015 PCM
49    DS-070-2015 MINSA
50      DS-071-2015 PCM
51      DS-072-2015 PCM
52      DS-073-2015 PCM
53    DS-074-2015 MINSA
54      DS-075-2015 PCM
55      DS-076-2015 PCM
Name: resolucion, dtype: object

In [42]:
def reso_info(x):
    
    regex_search = re.compile('([0-9]+)-([0-9]+)\s([A-Z]+)$')
    match = regex_search.search(x)
    
    return match.group(1), match.group(2), match.group(3)

In [43]:
# Código de la resolución

data['code_res'] = data['resolucion'].apply(lambda x: reso_info(x)[0])
data['code_res']

0     023
1     024
2     012
3     026
4     023
5     027
6     028
7     029
8     030
9     024
10    030
11    031
12    032
13    033
14    034
15    035
16    036
17    037
18    038
19    039
20    040
21    041
22    042
23    043
24    044
25    045
26    046
27    047
28    048
29    049
30    050
31    051
32    052
33    053
34    054
35    055
36    056
37    057
38    058
39    059
40    060
41    062
42    063
43    064
44    065
45     06
46    067
47    068
48    069
49    070
50    071
51    072
52    073
53    074
54    075
55    076
Name: code_res, dtype: object

In [44]:
# Año de emisión de la resolución

data['year_res'] = data['resolucion'].apply(lambda x: reso_info(x)[1])
data['year_res']

0     2015
1     2015
2     2014
3     2016
4     2015
5     2015
6     2015
7     2016
8     2014
9     2012
10    2015
11    2015
12    2015
13    2015
14    2015
15    2015
16    2015
17    2015
18    2015
19    2015
20    2015
21    2015
22    2015
23    2015
24    2015
25    2015
26    2015
27    2015
28    2015
29    2015
30    2015
31    2015
32    2015
33    2015
34    2015
35    2015
36    2015
37    2015
38    2015
39    2015
40    2015
41    2015
42    2015
43    2015
44    2015
45    2015
46    2015
47    2015
48    2015
49    2015
50    2015
51    2015
52    2015
53    2015
54    2015
55    2015
Name: year_res, dtype: object

In [45]:
# Entidad pública que emite la resolución

data['entidad_res'] = data['resolucion'].apply(lambda x: reso_info(x)[2])
data['entidad_res']

0       PCM
1       PCM
2     MINSA
3       PCM
4     MINSA
5       PCM
6       PCM
7     MINSA
8       PCM
9       PCM
10      PCM
11      PCM
12      PCM
13    MINSA
14      PCM
15      PCM
16      PCM
17      PCM
18      PCM
19    MINSA
20      PCM
21    MINSA
22      PCM
23    MINSA
24      PCM
25      PCM
26      PCM
27    MINSA
28      PCM
29      PCM
30    MINSA
31      PCM
32      PCM
33      PCM
34      PCM
35      PCM
36      PCM
37    MINSA
38      PCM
39      PCM
40    MINSA
41      PCM
42      PCM
43    MINSA
44      PCM
45      PCM
46      PCM
47      PCM
48      PCM
49    MINSA
50      PCM
51      PCM
52      PCM
53    MINSA
54      PCM
55      PCM
Name: entidad_res, dtype: object

In [46]:
# extraer usuario de correo 

correo = "rmendozu4am@pup.edu.pe"

# extraer solo la información antes del @

'rmendozu4am'

# str.contains

- Evalua si la cadena de caracter contiene cierto partrón de texto

In [47]:
data['dGobreg'] =  np.where(data['institución_ruc'].str.contains('(^G)|(^R)', regex=True),1,0)
data['dGobreg']

0     1
1     0
2     1
3     0
4     1
5     1
6     1
7     1
8     1
9     1
10    0
11    0
12    1
13    1
14    1
15    1
16    1
17    0
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    0
29    1
30    1
31    1
32    1
33    1
34    1
35    0
36    1
37    1
38    1
39    1
40    1
41    1
42    1
43    1
44    1
45    0
46    1
47    1
48    1
49    1
50    1
51    1
52    0
53    1
54    1
55    1
Name: dGobreg, dtype: int32

In [48]:
data['dMinsa'] =  np.where(data['institución_ruc'].str.contains('^M', na = False),1,0)
data['dMinsa']

0     0
1     1
2     0
3     1
4     0
5     0
6     0
7     0
8     0
9     0
10    1
11    1
12    0
13    0
14    0
15    0
16    0
17    1
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    1
29    0
30    0
31    0
32    0
33    0
34    0
35    1
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    1
46    0
47    0
48    0
49    0
50    0
51    0
52    1
53    0
54    0
55    0
Name: dMinsa, dtype: int32

# Look around

- Extrae lo que extá alrededor de un patrón de texto

In [49]:
# positive lookahead (?=)

regex = re.compile("\d+\:\d+(?= am)")

data['apertura1'] = data['horario'].apply(lambda x: re.search("\d+\:\d+(?= am)",x).group())
data['apertura1']

0      8:00
1      8:00
2      9:00
3      8:00
4      8:15
5      8:00
6      8:00
7      9:00
8      8:00
9      8:00
10     8:00
11     8:45
12     8:00
13     8:00
14     9:00
15     8:00
16     8:00
17    10:00
18     8:00
19     8:00
20     7:00
21     8:00
22     8:00
23    10:00
24     8:00
25     8:00
26     8:15
27     8:00
28     8:00
29     8:00
30     8:30
31     8:00
32     8:00
33     8:45
34     8:00
35     8:00
36     8:00
37     8:30
38     8:00
39     8:00
40     8:00
41     8:00
42     8:00
43     8:00
44     8:00
45     8:00
46     9:00
47     8:00
48     8:00
49     8:00
50     8:00
51     9:00
52     8:00
53     8:00
54     8:00
55    10:00
Name: apertura1, dtype: object

In [50]:
# positive lookbehind (?<=)

regex = re.compile("(?<=apertura )[\d+\:]+")
data['apertura3'] = data['horario'].apply(lambda x: regex.search(x).group())
data['apertura3']

0      8:00
1      8:00
2      9:00
3      8:00
4      8:15
5      8:00
6      8:00
7      9:00
8      8:00
9      8:00
10     8:00
11     8:45
12     8:00
13     8:00
14     9:00
15     8:00
16     8:00
17    10:00
18     8:00
19     8:00
20     7:00
21     8:00
22     8:00
23    10:00
24     8:00
25     8:00
26     8:15
27     8:00
28     8:00
29     8:00
30     8:30
31     8:00
32     8:00
33     8:45
34     8:00
35     8:00
36     8:00
37     8:30
38     8:00
39     8:00
40     8:00
41     8:00
42     8:00
43     8:00
44     8:00
45     8:00
46     9:00
47     8:00
48     8:00
49     8:00
50     8:00
51     9:00
52     8:00
53     8:00
54     8:00
55    10:00
Name: apertura3, dtype: object

In [51]:
# negative lookbehind (?<!)

regex = re.compile("(?<=apertura )[\d+\:]+")
data['cierre1'] = data['horario'].apply(lambda x: regex.search(x).group())
data['cierre1']

0      8:00
1      8:00
2      9:00
3      8:00
4      8:15
5      8:00
6      8:00
7      9:00
8      8:00
9      8:00
10     8:00
11     8:45
12     8:00
13     8:00
14     9:00
15     8:00
16     8:00
17    10:00
18     8:00
19     8:00
20     7:00
21     8:00
22     8:00
23    10:00
24     8:00
25     8:00
26     8:15
27     8:00
28     8:00
29     8:00
30     8:30
31     8:00
32     8:00
33     8:45
34     8:00
35     8:00
36     8:00
37     8:30
38     8:00
39     8:00
40     8:00
41     8:00
42     8:00
43     8:00
44     8:00
45     8:00
46     9:00
47     8:00
48     8:00
49     8:00
50     8:00
51     9:00
52     8:00
53     8:00
54     8:00
55    10:00
Name: cierre1, dtype: object

In [52]:
# negative lookbahead (?!)

regex = re.compile("[\d*\,]+(?!\$)")
data['pres_soles'] = data['presupuesto'].apply(lambda x: regex.search(x).group())
data['pres_soles']

0     1,255,546
1     1,255,546
2     1,255,546
3     1,255,546
4     1,255,546
5     1,255,546
6     1,255,546
7     1,255,546
8     1,255,546
9     1,255,546
10    1,255,546
11    1,255,546
12    1,255,546
13    1,255,546
14    1,255,546
15    1,255,546
16    1,255,546
17    1,255,546
18    1,255,546
19    1,255,546
20    1,255,546
21    1,255,546
22    1,255,546
23    1,255,546
24    1,255,546
25    1,255,546
26    1,255,546
27    1,255,546
28    1,255,546
29    1,255,546
30    1,255,546
31    1,255,546
32    1,255,546
33    1,255,546
34    1,255,546
35    1,255,546
36    1,255,546
37    1,255,546
38    1,255,546
39    1,255,546
40    1,255,546
41    1,255,546
42    1,255,546
43    1,255,546
44    1,255,546
45    1,255,546
46    1,255,546
47    1,255,546
48    1,255,546
49    1,255,546
50    1,255,546
51    1,255,546
52    1,255,546
53    1,255,546
54    1,255,546
55    1,255,546
Name: pres_soles, dtype: object

In [53]:
# retirar tildes del texto

data['presupuesto'] = data['presupuesto'].apply(unidecode.unidecode)

In [54]:
data['presupuesto']

0     soles1,255,546S/. Dolares300,125$
1                      ses1,255,546S/.
2     soles1,255,546S/. dolares300,125$
3     soles1,255,546S/. Dolares300,125$
4     soles1,255,546S/. Dolares300,125$
5      soes1,255,546S/. Dolares300,125$
6       soles1,255,546S/. Doles300,125$
7     soles1,255,546S/. Dolares300,125$
8     soles1,255,546S/. Dolares300,125$
9     soles1,255,546S/. Dolares300,125$
10    soles1,255,546S/. Dolares300,125$
11    soles1,255,546S/. Dolares300,125$
12    soles1,255,546S/. Dolares300,125$
13        sos1,255,546S/. Dolas300,125$
14    soles1,255,546S/. Dolares300,125$
15    soles1,255,546S/. Dolares300,125$
16                    soles1,255,546S/.
17    soles1,255,546S/. Dolares300,125$
18    soles1,255,546S/. Dolares300,125$
19    soles1,255,546S/. Dolares300,125$
20    soles1,255,546S/. Dolares300,125$
21    soles1,255,546S/. Dolares300,125$
22    soles1,255,546S/. Dolares300,125$
23    soles1,255,546S/. Dolares300,125$
24    soles1,255,546S/. Dolares300,125$
25    soles1,255,546S/. Dolares300,125$
26                   soles1,255,546S/.
27    soles1,255,546S/. Dolares300,125$
28    soles1,255,546S/. Dolares300,125$
29    soles1,255,546S/. Dolares300,125$
30      soles1,255,546S/. Doles300,125$
31    soles1,255,546S/. Dolares300,125$
32    soles1,255,546S/. Dolares300,125$
33    soles1,255,546S/. Dolares300,125$
34    soles1,255,546S/. Dolares300,125$
35    soles1,255,546S/. Dolares300,125$
36    soles1,255,546S/. Dolares300,125$
37                   soles1,255,546S/.
38    soles1,255,546S/. Dolares300,125$
39    soles1,255,546S/. Dolares300,125$
40    soles1,255,546S/. Dolares300,125$
41    soles1,255,546S/. Dolares300,125$
42    soles1,255,546S/. Dolares300,125$
43      sos1,255,546S/. Dolares300,125$
44    soles1,255,546S/. Dolares300,125$
45    soles1,255,546S/. Dolares300,125$
46                   soles1,255,546S/.
47    soles1,255,546S/. Dolares300,125$
48      soles1,255,546S/. Dolas300,125$
49    soles1,255,546S/. Dolares300,125$
50      ses1,255,546S/. Dolares300,125$
51    soles1,255,546S/. Dolares300,125$
52    soles1,255,546S/. Dolares300,125$
53                    soles1,255,546S/.
54    soles1,255,546S/. Dolares300,125$
55    soles1,255,546S/. Dolares300,125$
Name: presupuesto, dtype: object

In [55]:

#%% Segunda aplicación, filtro de filas

junin = pd.read_excel("../../data/Region_Junin.xlsx")

# select districs that contanis "AC"

junin.loc[ junin['District'].str.contains('AC') ]

junin.loc[junin['Place'].str.contains('pacha', na = False, flags = re.I)]

# na = False ignora los missing

# re.I ignoring capital o lower letters

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
49,49,JUNIN,JAUJA,C.PACAPACHA,1,7,8,24.0,18,42,...,25.0,50.0,25.0,25.0,0.0,NaN,0.0,50.0,0.0,0
140,140,JUNIN,CHONGOS,CARHUAPACHA,2,1,3,18.0,17,35,...,18.0,38.0,20.0,18.0,0.0,0.0,0.0,33.0,5.0,0
160,160,JUNIN,HUAYUCACHI,PACHA,18,9,27,31.0,12,43,...,21.0,70.0,49.0,21.0,0.0,0.0,0.0,70.0,0.0,0
183,183,JUNIN,OROYA,PACHA,2,4,6,7.0,3,10,...,7.0,16.0,9.0,7.0,0.0,0.0,0.0,16.0,0.0,0

In [56]:
 # Ignoring format re.I 

junin.loc[junin['District'].str.contains('CIUDAD', flags = re.I)]

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
0,0,JUNIN,CIUDAD DEL CERRO,C.CIUDAD DEL CERRO,65,46,111,297.0,171,468,...,209.0,544.0,361.0,216.0,1.0,1.0,4.0,284.0,290.0,1
1,1,JUNIN,CIUDAD DEL CERRO,P.YANACANCHA,1,3,4,49.0,47,96,...,50.0,100.0,50.0,50.0,0.0,0.0,0.0,100.0,0.0,0
2,2,JUNIN,CIUDAD DEL CERRO,VICO,1,0,1,46.0,25,71,...,25.0,72.0,47.0,25.0,0.0,0.0,0.0,69.0,3.0,0
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25.0,19,44,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,25.0,25.0,0
4,4,JUNIN,CIUDAD DEL CERRO,PASCO,4,4,8,21.0,21,42,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,37.0,13.0,0
5,5,JUNIN,CIUDAD DEL CERRO,NaN,6,7,13,44.0,43,87,...,50.0,100.0,50.0,50.0,0.0,0.0,0.0,65.0,35.0,0
6,6,JUNIN,CIUDAD DEL CERRO,CAJAMARQUILLA,9,8,17,31.0,39,70,...,47.0,87.0,40.0,47.0,0.0,0.0,0.0,87.0,0.0,0
7,7,JUNIN,CIUDAD DEL CERRO,CAICO,18,23,41,90.0,77,167,...,99.0,206.0,108.0,100.0,0.0,0.0,4.0,175.0,29.0,0
8,8,JUNIN,CIUDAD DEL CERRO,ROCO,7,4,11,42.0,19,61,...,23.0,72.0,49.0,23.0,0.0,0.0,0.0,70.0,NaN,0
9,9,JUNIN,CIUDAD DEL CERRO,NaN,16,8,24,26.0,25,51,...,33.0,75.0,42.0,33.0,0.0,0.0,0.0,73.0,NaN,0
10,10,JUNIN,CIUDAD DEL CERRO,P.QUINUA,8,6,14,17.0,19,36,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,50.0,0.0,0
11,11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10.0,12,22,...,18.0,30.0,12.0,18.0,0.0,0.0,0.0,NaN,6.0,0
12,12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38.0,32,70,...,46.0,96.0,50.0,46.0,0.0,0.0,0.0,96.0,0.0,0
13,13,JUNIN,CIUDAD DEL CERRO,H.SAN ANDRÉS,8,0,8,17.0,25,42,...,25.0,50.0,25.0,NaN,0.0,0.0,0.0,44.0,6.0,0

In [57]:
# If regex is False, then contains seeks "^hu" literaly 
# # Beginning word with hu

junin.loc[junin['District'].str.contains('^hu', flags = re.I, na = False, regex = True)]

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
14,14,JUNIN,HUAYLLAY,P.HUALLAY,5,11,16,NaN,37,92,...,48.0,108.0,60.0,48.0,0.0,0.0,0.0,92.0,16.0,0
15,15,JUNIN,HUAYLLAY,C.HUAYCHAO,1,0,1,24.0,8,32,...,8.0,33.0,25.0,8.0,0.0,0.0,0.0,33.0,0.0,0
16,16,JUNIN,HUAYLLAY,COCHAMARCA,0,3,3,11.0,8,19,...,11.0,22.0,11.0,11.0,0.0,0.0,0.0,22.0,0.0,0
66,66,JUNIN,HUARIPAMPA,P.HUARIPAMPA,21,34,55,73.0,78,151,...,112.0,196.0,94.0,112.0,0.0,0.0,0.0,206.0,0.0,0
67,67,JUNIN,HUARIPAMPA,A.PARCO,10,4,14,88.0,80,168,...,78.0,170.0,98.0,84.0,0.0,0.0,2.0,180.0,0.0,0
68,68,JUNIN,HUARIPAMPA,PACCHA,12,9,21,77.0,65,142,...,74.0,162.0,89.0,74.0,0.0,0.0,0.0,163.0,0.0,0
69,69,JUNIN,HUARIPAMPA,CANCHAPUNCO,1,6,7,23.0,18,41,...,24.0,48.0,24.0,24.0,0.0,0.0,0.0,48.0,0.0,0
70,70,JUNIN,HUARIPAMPA,C.ULLUSCA,4,1,5,21.0,14,35,...,15.0,40.0,25.0,15.0,0.0,0.0,0.0,40.0,0.0,0
71,71,JUNIN,HUARIPAMPA,CANCHAS,2,5,7,16.0,12,28,...,17.0,35.0,18.0,17.0,0.0,0.0,0.0,35.0,0.0,0
106,106,JUNIN,HUANCAYO,P.HUANCAYO,184,184,368,950.0,957,1907,...,1089.0,2164.0,1132.0,1141.0,2.0,0.0,308.0,1367.0,598.0,2
107,107,JUNIN,HUANCAYO,CAJAS,40,64,104,187.0,134,321,...,198.0,413.0,227.0,198.0,0.0,0.0,11.0,222.0,192.0,0
108,108,JUNIN,HUANCAYO,PACCHA,18,24,42,89.0,71,160,...,94.0,200.0,107.0,95.0,0.0,0.0,8.0,58.0,136.0,0
153,153,JUNIN,HUAYUCACHI,P.HUAYUCACHI,40,32,72,110.0,74,184,...,106.0,256.0,150.0,106.0,0.0,0.0,1.0,240.0,15.0,0
154,154,JUNIN,HUAYUCACHI,HUAMANMARCA,9,10,19,42.0,23,65,...,33.0,84.0,51.0,33.0,0.0,0.0,0.0,84.0,0.0,0
155,155,JUNIN,HUAYUCACHI,NaN,12,19,31,88.0,71,159,...,90.0,190.0,100.0,90.0,0.0,0.0,0.0,190.0,0.0,0
156,156,JUNIN,HUAYUCACHI,CACAS,19,11,30,31.0,39,70,...,50.0,100.0,50.0,50.0,0.0,0.0,0.0,100.0,0.0,0
157,157,JUNIN,HUAYUCACHI,HUARAPUQUIO,12,29,41,51.0,49,100,...,78.0,141.0,63.0,78.0,0.0,0.0,0.0,141.0,0.0,0
158,158,JUNIN,HUAYUCACHI,CULLHUAS,5,5,10,39.0,26,65,...,31.0,75.0,44.0,31.0,0.0,0.0,0.0,75.0,0.0,0
159,159,JUNIN,HUAYUCACHI,RETAMA,12,12,24,38.0,21,59,...,33.0,83.0,50.0,33.0,0.0,0.0,0.0,83.0,0.0,0
160,160,JUNIN,HUAYUCACHI,PACHA,18,9,27,31.0,12,43,...,21.0,70.0,49.0,21.0,0.0,0.0,0.0,70.0,0.0,0

In [58]:
 # regex True para identificar la expression regular, na = False para ignorar missing

# Ending word

junin.loc[junin['Place'].str.contains('ro$', flags = re.I, na = False, regex = True)]


junin.loc[junin['Place'].str.contains('ca$', flags = re.I, na = False, regex = True)]

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
3,3,JUNIN,CIUDAD DEL CERRO,RANCA,0,6,6,25.0,19,44,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,25.0,25.0,0
11,11,JUNIN,CIUDAD DEL CERRO,H.PARIAHUANCA,2,6,8,10.0,12,22,...,18.0,30.0,12.0,18.0,0.0,0.0,0.0,NaN,6.0,0
12,12,JUNIN,CIUDAD DEL CERRO,P.SULLUMARCA,12,14,26,38.0,32,70,...,46.0,96.0,50.0,46.0,0.0,0.0,0.0,96.0,0.0,0
16,16,JUNIN,HUAYLLAY,COCHAMARCA,0,3,3,11.0,8,19,...,11.0,22.0,11.0,11.0,0.0,0.0,0.0,22.0,0.0,0
22,22,JUNIN,CHACAYÁN,ANTAPIRCA,20,15,35,29.0,60,89,...,75.0,124.0,49.0,75.0,0.0,0.0,0.0,124.0,0.0,0
35,35,JUNIN,YANAHUANCA,P.YANAHUANCA,6,18,24,75.0,82,157,...,100.0,181.0,81.0,100.0,0.0,0.0,15.0,116.0,47.0,3
36,36,JUNIN,YANAHUANCA,HUAYLACIRCA,4,4,8,21.0,21,42,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,50.0,0.0,0
38,38,JUNIN,YANAHUANCA,ANDUCHACA,1,6,7,20.0,15,35,...,21.0,42.0,21.0,21.0,0.0,0.0,0.0,40.0,2.0,0
41,41,JUNIN,YANAHUANCA,MICHIVILCA,7,3,10,30.0,33,63,...,36.0,73.0,37.0,36.0,0.0,0.0,0.0,73.0,0.0,0
45,45,JUNIN,YANAHUANCA,CHAUPIMARCA,15,8,23,35.0,14,49,...,22.0,72.0,50.0,22.0,0.0,0.0,25.0,NaN,0.0,0
52,52,JUNIN,JAUJA,PACA,1,4,5,84.0,52,136,...,56.0,141.0,85.0,56.0,0.0,0.0,6.0,141.0,0.0,0
70,70,JUNIN,HUARIPAMPA,C.ULLUSCA,4,1,5,21.0,14,35,...,15.0,40.0,25.0,15.0,0.0,0.0,0.0,40.0,0.0,0
80,80,JUNIN,ACOLLA,CURICACA,8,3,11,25.0,10,35,...,13.0,46.0,33.0,13.0,0.0,0.0,0.0,46.0,0.0,0
109,109,JUNIN,CHUPACA,P.CHUPACA,82,77,159,451.0,316,767,...,393.0,922.0,533.0,393.0,0.0,0.0,44.0,585.0,297.0,0
115,115,JUNIN,CHUPACA,COPCA,5,12,17,61.0,57,118,...,69.0,135.0,66.0,69.0,0.0,0.0,0.0,132.0,3.0,0
117,117,JUNIN,CHUPACA,HUAMANCACA,27,27,54,73.0,71,144,...,98.0,198.0,100.0,98.0,0.0,0.0,0.0,153.0,45.0,0
141,141,JUNIN,CHONGOS,A.HUAMANCACA,32,28,60,90.0,73,163,...,101.0,223.0,122.0,101.0,0.0,0.0,0.0,53.0,170.0,0
144,144,JUNIN,SICAYA,C.CACHICAMARCA,3,5,8,22.0,24,46,...,29.0,54.0,25.0,29.0,0.0,0.0,0.0,54.0,0.0,0
145,145,JUNIN,COLCA,P.COLCA,5,6,11,79.0,67,146,...,73.0,157.0,84.0,73.0,0.0,0.0,0.0,107.0,50.0,0
150,150,JUNIN,COLCA,POTACA,22,9,31,28.0,7,35,...,16.0,65.0,50.0,16.0,0.0,0.0,0.0,66.0,0.0,0
154,154,JUNIN,HUAYUCACHI,HUAMANMARCA,9,10,19,42.0,23,65,...,33.0,84.0,51.0,33.0,0.0,0.0,0.0,84.0,0.0,0
178,178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132.0,151,283,...,204.0,389.0,185.0,204.0,0.0,0.0,30.0,197.0,162.0,0
192,192,JUNIN,CHACAPALCA,CHACAPALCA,1,0,1,71.0,0,71,...,0.0,72.0,72.0,0.0,0.0,0.0,0.0,35.0,39.0,0

In [59]:
# match : a , c , ac

junin.loc[junin['Place'].str.contains('^ac*', flags = re.I, na = False, regex = True)]

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
22,22,JUNIN,CHACAYÁN,ANTAPIRCA,20,15,35,29.0,60,89,...,75.0,124.0,49.0,75.0,0.0,0.0,0.0,124.0,0.0,0
24,24,JUNIN,CAYNA,A. COLPAS,0,0,0,26.0,0,26,...,0.0,26.0,26.0,0.0,0.0,0.0,0.0,26.0,0.0,0
34,34,JUNIN,CAYNA,A.YAPOC,3,0,3,32.0,0,32,...,0.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,0.0,0
38,38,JUNIN,YANAHUANCA,ANDUCHACA,1,6,7,20.0,15,35,...,21.0,42.0,21.0,21.0,0.0,0.0,0.0,40.0,2.0,0
48,48,JUNIN,JAUJA,A.CHUNÁN,12,11,23,45.0,21,66,...,32.0,89.0,57.0,32.0,0.0,0.0,0.0,89.0,0.0,0
51,51,JUNIN,JAUJA,A.HUERTAS,22,38,60,103.0,87,190,...,125.0,246.0,125.0,125.0,0.0,0.0,0.0,195.0,55.0,0
54,54,JUNIN,JAUJA,ATAURA,24,22,46,74.0,68,142,...,90.0,182.0,98.0,90.0,0.0,0.0,NaN,104.0,84.0,0
58,58,JUNIN,JAUJA,A.PAUCÁN,21,13,34,85.0,69,154,...,82.0,187.0,106.0,82.0,0.0,0.0,0.0,65.0,123.0,0
61,61,JUNIN,APATA,A.SAN LORENZO,11,10,21,56.0,50,106,...,60.0,126.0,67.0,60.0,0.0,0.0,0.0,38.0,89.0,0
64,64,JUNIN,ORCOTUNA,A.VICSO,6,7,13,44.0,43,87,...,50.0,100.0,50.0,50.0,0.0,0.0,0.0,15.0,85.0,0
67,67,JUNIN,HUARIPAMPA,A.PARCO,10,4,14,88.0,80,168,...,78.0,170.0,98.0,84.0,0.0,0.0,2.0,180.0,0.0,0
78,78,JUNIN,ACOLLA,ACAYA,2,2,4,29.0,21,50,...,23.0,54.0,31.0,23.0,0.0,0.0,0.0,54.0,0.0,0
85,85,JUNIN,CINCOS,ARAMACHAY,0,5,5,52.0,31,83,...,36.0,83.0,52.0,36.0,0.0,0.0,0.0,75.0,13.0,0
87,87,JUNIN,MITO,A.CHAMBARÁ,19,12,31,57.0,38,95,...,50.0,124.0,43.0,50.0,0.0,0.0,0.0,74.0,52.0,0
90,90,JUNIN,MITO,A.ACO,39,23,62,136.0,52,188,...,75.0,250.0,175.0,75.0,0.0,0.0,0.0,214.0,36.0,0
99,99,JUNIN,CONCEPCIÓN,A.ALAYO,3,8,11,22.0,29,51,...,37.0,62.0,25.0,37.0,0.0,0.0,0.0,62.0,0.0,0
110,110,JUNIN,CHUPACA,A.ISCOS,31,30,61,154.0,119,273,...,149.0,329.0,185.0,149.0,0.0,0.0,0.0,280.0,54.0,0
111,111,JUNIN,CHUPACA,ANTAPAMPA,9,7,16,16.0,18,34,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,50.0,0.0,0
119,119,JUNIN,CHUPACA,AHUAC,41,36,77,110.0,114,224,...,150.0,296.0,151.0,150.0,0.0,0.0,0.0,179.0,122.0,0
120,120,JUNIN,CHUPACA,ACAC,22,12,34,45.0,43,88,...,55.0,122.0,67.0,55.0,0.0,0.0,14.0,108.0,0.0,0
126,126,JUNIN,SAN GERÓNIMO,A.INGENIO,18,6,24,77.0,75,152,...,81.0,176.0,95.0,81.0,0.0,0.0,57.0,72.0,47.0,0
130,130,JUNIN,SAPALLANGA,A.LA PUNTA,32,17,49,115.0,49,164,...,66.0,213.0,147.0,66.0,0.0,0.0,3.0,210.0,0.0,0
141,141,JUNIN,CHONGOS,A.HUAMANCACA,32,28,60,90.0,73,163,...,101.0,223.0,122.0,101.0,0.0,0.0,0.0,53.0,170.0,0
143,143,JUNIN,SICAYA,A.HUANCHAC,7,17,24,72.0,53,125,...,70.0,149.0,79.0,70.0,0.0,0.0,0.0,44.0,105.0,0
146,146,JUNIN,COLCA,A.CHACAPAMPA,27,17,44,69.0,55,124,...,72.0,168.0,96.0,72.0,0.0,0.0,24.0,144.0,0.0,0
173,173,JUNIN,JUNÍN,ACONCOCHA,2,2,4,23.0,23,46,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,50.0,0.0,0
178,178,JUNIN,ACOBAMBA,A.PALCA,53,53,106,132.0,151,283,...,204.0,389.0,185.0,204.0,0.0,0.0,30.0,197.0,162.0,0

In [60]:
# match : ac (strict)

junin.loc[junin['Place'].str.contains('^ac+', flags = re.I, na = False, regex = True)]

,Unnamed: 0,Region,District,Place,4_6_years_men,4_6_years_women,4_6_years_total,6_14_years_men,6_14_years_women,6_14_years_total,...,not_finished_instr_women,not_finished_instr_total,peruvian_men,peruvian_women,foreign_men,foreign_women,whites,natives,mestizos,blacks
78,78,JUNIN,ACOLLA,ACAYA,2,2,4,29.0,21,50,...,23.0,54.0,31.0,23.0,0.0,0.0,0.0,54.0,0.0,0
120,120,JUNIN,CHUPACA,ACAC,22,12,34,45.0,43,88,...,55.0,122.0,67.0,55.0,0.0,0.0,14.0,108.0,0.0,0
173,173,JUNIN,JUNÍN,ACONCOCHA,2,2,4,23.0,23,46,...,25.0,50.0,25.0,25.0,0.0,0.0,0.0,50.0,0.0,0

## Fechas

In [61]:
data['fecha_apertura_date'] = pd.to_datetime(data['fecha_apertura1']
                                             , dayfirst = True).dt.strftime('%d/%m/%Y')

# dayfirst = True se indica la columna fecha_apertura 
# empieza con el día, luego con strftime se indica el formato dia/mes/año de la fecha

In [62]:
data['fecha_apertura_date']

0     28/06/2015
1     01/10/2015
2            NaN
3     10/07/2018
4     28/08/2018
5     02/11/2018
6     31/12/2018
7     01/07/2019
8     01/10/2019
9     10/10/2019
10    05/11/2019
11    15/11/2019
12           NaN
13    15/12/2019
14    26/06/2020
15    01/10/2020
16    01/10/2020
17    02/11/2020
18    02/11/2020
19    03/11/2020
20    04/11/2020
21    04/11/2020
22    11/11/2020
23           NaN
24    13/11/2020
25    14/11/2020
26    15/11/2020
27    19/11/2020
28    01/12/2020
29    15/06/2021
30    29/06/2021
31    08/08/2021
32           NaN
33    12/11/2021
34    01/01/2019
35    01/02/2021
36    03/01/2020
37    01/04/2019
38    01/06/2015
39    01/06/2015
40    01/06/2015
41    01/06/2015
42    01/06/2018
43    01/06/2021
44    01/07/2017
45    01/07/2018
46    01/08/2015
47    01/08/2018
48    01/08/2018
49           NaN
50    01/08/2018
51    01/08/2019
52    01/09/2018
53    01/10/2018
54    01/10/2019
55    01/10/2019
Name: fecha_apertura_date, dtype: object

# Map Coordinates (Capac Ñan)

In [2]:
base1 = pd.read_excel(r"../../data/map_coordinates.xlsx")

In [3]:
capac = base1.copy()

In [4]:
# Data clean 

data1 = capac[capac.ID.isna()].reset_index(drop = True)
data2 = capac[~ capac.ID.isna()].reset_index(drop = True)

In [5]:
data2.shape

(137, 6)

In [6]:
data2['Coordinates2'] = data1['Coordinates']

In [7]:
data2

,ID,Name & Location,State Party,Coordinates,Property,Buffer Zone,Coordinates2
0,1459-001,AR-QGE-01/C-2011,Argentina,S23 22 0,0.494 ha,18.179 ha,W64 58 0
1,1459-002,AR-SRT-02/CS-2011,Argentina,S24 26 0,15.18 ha,423.73 ha,W65 57 0
2,1459-003,AR-ACHC-03/CS-2011,Argentina,S24 34 59.99,16.25 ha,165.05 ha,W66 1 59.99
3,1459-004,AR-PPG-05/CS-2011,Argentina,S24 49 0,3.51 ha,51.61 ha,W66 9 0
4,1459-005,AR-LLU-07/CS-2011,Argentina,S24 41 0,261.53 ha,"14,787.839 ha",W68 31 0
...,...,...,...,...,...,...,...
132,1459-133,PE-HH-56/CS-2011,Peru,S8 45 59,15.45 ha,486.691 ha,W77 27 3
133,1459-134,PE-HH-57/CS-2011,Peru,S8 23 46,15.25 ha,387.392 ha,W77 46 21
134,1459-135,PE-HH-58/CS-2011,Peru,S8 19 48,4.41 ha,246.522 ha,W77 49 10
135,1459-136,PE-HH-59/CS-2011,Peru,S7 56 15,3.98 ha,"1,266.603 ha",W78 0 44
136,1459-137,PE-ALP-60/CS-2011,Peru,S4 42 17,37.22 ha,"1,502.79 ha",W79 34 27

In [8]:
def convert_gps(x):
        
    signo = -1 if re.search('[swSWoO-]', x ) else 1
    
    regex = re.compile('[^\d+\s\.]') # Todo lo que sea diferente a digitos, especio y el punto
    h, m , s = str.split( regex.sub('', x ) )
    
    return signo*(float(h) + float(m)/60 + float(s)/3600)

In [9]:
data2['latitud'] = data2.Coordinates.map(convert_gps)
data2['longitud'] = data2.Coordinates2.map(convert_gps)

In [10]:
data2

,ID,Name & Location,State Party,Coordinates,Property,Buffer Zone,Coordinates2,latitud,longitud
0,1459-001,AR-QGE-01/C-2011,Argentina,S23 22 0,0.494 ha,18.179 ha,W64 58 0,-23.366667,-64.966667
1,1459-002,AR-SRT-02/CS-2011,Argentina,S24 26 0,15.18 ha,423.73 ha,W65 57 0,-24.433333,-65.950000
2,1459-003,AR-ACHC-03/CS-2011,Argentina,S24 34 59.99,16.25 ha,165.05 ha,W66 1 59.99,-24.583331,-66.033331
3,1459-004,AR-PPG-05/CS-2011,Argentina,S24 49 0,3.51 ha,51.61 ha,W66 9 0,-24.816667,-66.150000
4,1459-005,AR-LLU-07/CS-2011,Argentina,S24 41 0,261.53 ha,"14,787.839 ha",W68 31 0,-24.683333,-68.516667
...,...,...,...,...,...,...,...,...,...
132,1459-133,PE-HH-56/CS-2011,Peru,S8 45 59,15.45 ha,486.691 ha,W77 27 3,-8.766389,-77.450833
133,1459-134,PE-HH-57/CS-2011,Peru,S8 23 46,15.25 ha,387.392 ha,W77 46 21,-8.396111,-77.772500
134,1459-135,PE-HH-58/CS-2011,Peru,S8 19 48,4.41 ha,246.522 ha,W77 49 10,-8.330000,-77.819444
135,1459-136,PE-HH-59/CS-2011,Peru,S7 56 15,3.98 ha,"1,266.603 ha",W78 0 44,-7.937500,-78.012222
136,1459-137,PE-ALP-60/CS-2011,Peru,S4 42 17,37.22 ha,"1,502.79 ha",W79 34 27,-4.704722,-79.574167

In [11]:
data_capac = data2[data2["State Party"] == "Peru"]

In [12]:
data_capac

,ID,Name & Location,State Party,Coordinates,Property,Buffer Zone,Coordinates2,latitud,longitud
83,1459-084,PE-PH-01/CS-2011,Peru,S13 30 0,8.23 ha,205.327 ha,W71 58 0,-13.500000,-71.966667
84,1459-085,PE-CD-02/CS-2011,Peru,S13 37 48,2.81 ha,"4,546.334 ha",W71 41 55,-13.630000,-71.698611
85,1459-086,PE-CD-03/C-2011,Peru,S13 57 10,1.36 ha,6.758 ha,W71 29 57,-13.952778,-71.499167
86,1459-087,PE-CD-04/CS-2011,Peru,S14 10 31,3.65 ha,"1,237.808 ha",W71 21 57,-14.175278,-71.365833
87,1459-088,PE-CD-06/C-2011,Peru,S14 41 15,11.24 ha,54.126 ha,W70 45 24,-14.687500,-70.756667
88,1459-089,PE-CD-08/C-2011,Peru,S15 9 49,13.69 ha,"4,667.481 ha",W70 17 17,-15.163611,-70.288056
89,1459-090,PE-CD-09/CS-2011,Peru,S15 46 46,10.24 ha,45.207 ha,W70 3 15,-15.779444,-70.054167
90,1459-091,PE-CD-10/C-2011,Peru,S15 52 23,1.25 ha,6.184 ha,W70 0 59,-15.873056,-70.016389
91,1459-092,PE-CD-11/C-2011,Peru,S15 52 54,1.78 ha,8.635 ha,W69 57 25,-15.881667,-69.956944
92,1459-093,PE-CD-12/C-2011,Peru,S16 12 17,2.34 ha,11.435 ha,W69 25 3,-16.204722,-69.417500
93,1459-094,PE-CD-13/C-2011,Peru,S16 15 57,2.74 ha,13.316 ha,W69 18 25,-16.265833,-69.306944
94,1459-095,PE-CD-14/C-2011,Peru,S16 18 13,4.64 ha,22.502 ha,W69 16 20,-16.303611,-69.272222
95,1459-096,PE-CD-15/C-2011,Peru,S16 25 55,2.25 ha,11.016 ha,W69 8 60,-16.431944,-69.150000
96,1459-097,PE-OL-16/CS-2011,Peru,S13 7 33,1.2 ha,338.993 ha,W72 5 36,-13.125833,-72.093333
97,1459-098,PE-OL-17/C-2011,Peru,S13 1 59.99,0.35 ha,"3,761.801 ha",W72 1 59.99,-13.033331,-72.033331
98,1459-099,PE-OL-18/CS-2011,Peru,S13 1 0,0.94 ha,NaN,W72 1 59.99,-13.016667,-72.033331
99,1459-100,PE-OL-19/CS-2011,Peru,S12 56 0,10.29 ha,NaN,W71 58 59.99,-12.933333,-71.983331
100,1459-101,PE-OL-21/CS-2011,Peru,S12 43 8,7.04 ha,"3,075.416 ha",W72 1 44,-12.718889,-72.028889
101,1459-102,PE-VCH-22/CS-2011,Peru,S13 9 42,7.05 ha,"514,025.937 ha",W72 54 34,-13.161667,-72.909444
102,1459-103,PE-VCH-23/CS-2011,Peru,S13 11 0,0.64 ha,NaN,W72 52 59.99,-13.183333,-72.883331
103,1459-104,PE-VCH-24/CS-2011,Peru,S13 43 59.99,1.18 ha,NaN,W72 52 59.99,-13.733331,-72.883331
104,1459-105,PE-VCH-26/CS-2011,Peru,S13 20 0,54 ha,NaN,W72 52 59.99,-13.333333,-72.883331
105,1459-106,PE-PQ-27/C-2011,Peru,S14 22 53,0.01 ha,1.176 ha,W71 29 2,-14.381389,-71.483889
106,1459-107,PE-XP-30/CS-2011,Peru,S12 3 11,159.09 ha,"3,530.268 ha",W75 58 21,-12.053056,-75.972500
107,1459-108,PE-XP-31/S-2011,Peru,S12 4 0,55.12 ha,NaN,W76 0 0,-12.066667,-76.000000
108,1459-109,PE-XP-32/C-2011,Peru,S12 8 23,3.26 ha,"2,031.926 ha",W76 13 25,-12.139722,-76.223611
109,1459-110,PE-XP-33/CS-2011,Peru,S12 4 34,41.66 ha,279.709 ha,W76 31 7,-12.076111,-76.518611
110,1459-111,PE-XP-34/C-2011,Peru,S12 1 34,3.03 ha,103.511 ha,W76 39 49,-12.026111,-76.663611
111,1459-112,PE-XP-35/S-2011,Peru,S12 1 30,3.22 ha,6.238 ha,W76 40 25,-12.025000,-76.673611
112,1459-113,PE-XP-36/S-2011,Peru,S12 2 11,89.16 ha,—,W76 42 11,-12.036389,-76.703056
113,1459-114,PE-XP-37/C-2011,Peru,S12 2 19,1.79 ha,67.339 ha,W76 43 15,-12.038611,-76.720833
114,1459-115,PE-XP-38/S-2011,Peru,S12 4 50,10.26 ha,—,W76 46 28,-12.080556,-76.774444
115,1459-116,PE-XP-39/S-2011,Peru,S12 5 1,32.81 ha,—,W76 45 56,-12.083611,-76.765556
116,1459-117,PE-XP-40/CS-2011,Peru,S12 15 12.08,460.31 ha,"1,829.26 ha",W76 54 16.09,-12.253356,-76.904469
117,1459-118,PE-HH-41/CS-2011,Peru,S9 53 8,796.32 ha,"4,856.44 ha",W76 48 29,-9.885556,-76.808056
118,1459-119,PE-HH-42/CS-2011,Peru,S9 51 29,10.57 ha,504.01 ha,W76 51 5,-9.858056,-76.851389
119,1459-120,PE-HH-43/CS-2011,Peru,S9 46 44,4.23 ha,508.013 ha,W76 53 24,-9.778889,-76.890000
120,1459-121,PE-HH-44/CS-2011,Peru,S9 40 57,24.27 ha,"1,743.418 ha",W76 51 14,-9.682500,-76.853889
121,1459-122,PE-HH-45/CS-2011,Peru,S9 37 59.99,32.96 ha,NaN,W76 57 0,-9.633331,-76.950000
122,1459-123,PE-HH-46/CS-2011,Peru,S9 32 54,13.29 ha,281.808 ha,W76 59 10,-9.548333,-76.986111
123,1459-124,PE-HH-47/CS-2011,Peru,S9 30 52,4.47 ha,85.039 ha,W77 1 14,-9.514444,-77.020556
124,1459-125,PE-HH-48/CS-2011,Peru,S9 28 59.99,3.447 ha,157.621 ha,W77 1 59.99,-9.483331,-77.033331
125,1459-126,PE-HH-49/CS-2011,Peru,S9 27 55,10.5 ha,"4,262.694 ha",W77 4 17,-9.465278,-77.071389
126,1459-127,PE-HH-50/C-2011,Peru,S9 25 59.99,2.77 ha,NaN,W77 4 59.99,-9.433331,-77.083331
127,1459-128,PE-HH-51/CS-2011,Peru,S9 16 8,6.43 ha,"1,516.547 ha",W77 9 37,-9.268889,-77.160278
128,1459-129,PE-HH-52/CS-2011,Peru,S9 7 14,19.99 ha,528.729 ha,W77 12 29,-9.120556,-77.208056
129,1459-130,PE-HH-53/CS-2011,Peru,S9 4 0,14.05 ha,NaN,W77 13 59.99,-9.066667,-77.233331
130,1459-131,PE-HH-54/C-2011,Peru,S8 54 20,4.94 ha,275.69 ha,W77 19 42,-8.905556,-77.328333
131,1459-132,PE-HH-55/C-2011,Peru,S8 50 44,6.15 ha,216.446 ha,W77 22 49,-8.845556,-77.380278
132,1459-133,PE-HH-56/CS-2011,Peru,S8 45 59,15.45 ha,486.691 ha,W77 27 3,-8.766389,-77.450833
133,1459-134,PE-HH-57/CS-2011,Peru,S8 23 46,15.25 ha,387.392 ha,W77 46 21,-8.396111,-77.772500
134,1459-135,PE-HH-58/CS-2011,Peru,S8 19 48,4.41 ha,246.522 ha,W77 49 10,-8.330000,-77.819444
135,1459-136,PE-HH-59/CS-2011,Peru,S7 56 15,3.98 ha,"1,266.603 ha",W78 0 44,-7.937500,-78.012222
136,1459-137,PE-ALP-60/CS-2011,Peru,S4 42 17,37.22 ha,"1,502.79 ha",W79 34 27,-4.704722,-79.574167

In [13]:
data_capac["Name & Location"].is_unique

True

In [14]:
data_capac

,ID,Name & Location,State Party,Coordinates,Property,Buffer Zone,Coordinates2,latitud,longitud
83,1459-084,PE-PH-01/CS-2011,Peru,S13 30 0,8.23 ha,205.327 ha,W71 58 0,-13.500000,-71.966667
84,1459-085,PE-CD-02/CS-2011,Peru,S13 37 48,2.81 ha,"4,546.334 ha",W71 41 55,-13.630000,-71.698611
85,1459-086,PE-CD-03/C-2011,Peru,S13 57 10,1.36 ha,6.758 ha,W71 29 57,-13.952778,-71.499167
86,1459-087,PE-CD-04/CS-2011,Peru,S14 10 31,3.65 ha,"1,237.808 ha",W71 21 57,-14.175278,-71.365833
87,1459-088,PE-CD-06/C-2011,Peru,S14 41 15,11.24 ha,54.126 ha,W70 45 24,-14.687500,-70.756667
88,1459-089,PE-CD-08/C-2011,Peru,S15 9 49,13.69 ha,"4,667.481 ha",W70 17 17,-15.163611,-70.288056
89,1459-090,PE-CD-09/CS-2011,Peru,S15 46 46,10.24 ha,45.207 ha,W70 3 15,-15.779444,-70.054167
90,1459-091,PE-CD-10/C-2011,Peru,S15 52 23,1.25 ha,6.184 ha,W70 0 59,-15.873056,-70.016389
91,1459-092,PE-CD-11/C-2011,Peru,S15 52 54,1.78 ha,8.635 ha,W69 57 25,-15.881667,-69.956944
92,1459-093,PE-CD-12/C-2011,Peru,S16 12 17,2.34 ha,11.435 ha,W69 25 3,-16.204722,-69.417500
93,1459-094,PE-CD-13/C-2011,Peru,S16 15 57,2.74 ha,13.316 ha,W69 18 25,-16.265833,-69.306944
94,1459-095,PE-CD-14/C-2011,Peru,S16 18 13,4.64 ha,22.502 ha,W69 16 20,-16.303611,-69.272222
95,1459-096,PE-CD-15/C-2011,Peru,S16 25 55,2.25 ha,11.016 ha,W69 8 60,-16.431944,-69.150000
96,1459-097,PE-OL-16/CS-2011,Peru,S13 7 33,1.2 ha,338.993 ha,W72 5 36,-13.125833,-72.093333
97,1459-098,PE-OL-17/C-2011,Peru,S13 1 59.99,0.35 ha,"3,761.801 ha",W72 1 59.99,-13.033331,-72.033331
98,1459-099,PE-OL-18/CS-2011,Peru,S13 1 0,0.94 ha,NaN,W72 1 59.99,-13.016667,-72.033331
99,1459-100,PE-OL-19/CS-2011,Peru,S12 56 0,10.29 ha,NaN,W71 58 59.99,-12.933333,-71.983331
100,1459-101,PE-OL-21/CS-2011,Peru,S12 43 8,7.04 ha,"3,075.416 ha",W72 1 44,-12.718889,-72.028889
101,1459-102,PE-VCH-22/CS-2011,Peru,S13 9 42,7.05 ha,"514,025.937 ha",W72 54 34,-13.161667,-72.909444
102,1459-103,PE-VCH-23/CS-2011,Peru,S13 11 0,0.64 ha,NaN,W72 52 59.99,-13.183333,-72.883331
103,1459-104,PE-VCH-24/CS-2011,Peru,S13 43 59.99,1.18 ha,NaN,W72 52 59.99,-13.733331,-72.883331
104,1459-105,PE-VCH-26/CS-2011,Peru,S13 20 0,54 ha,NaN,W72 52 59.99,-13.333333,-72.883331
105,1459-106,PE-PQ-27/C-2011,Peru,S14 22 53,0.01 ha,1.176 ha,W71 29 2,-14.381389,-71.483889
106,1459-107,PE-XP-30/CS-2011,Peru,S12 3 11,159.09 ha,"3,530.268 ha",W75 58 21,-12.053056,-75.972500
107,1459-108,PE-XP-31/S-2011,Peru,S12 4 0,55.12 ha,NaN,W76 0 0,-12.066667,-76.000000
108,1459-109,PE-XP-32/C-2011,Peru,S12 8 23,3.26 ha,"2,031.926 ha",W76 13 25,-12.139722,-76.223611
109,1459-110,PE-XP-33/CS-2011,Peru,S12 4 34,41.66 ha,279.709 ha,W76 31 7,-12.076111,-76.518611
110,1459-111,PE-XP-34/C-2011,Peru,S12 1 34,3.03 ha,103.511 ha,W76 39 49,-12.026111,-76.663611
111,1459-112,PE-XP-35/S-2011,Peru,S12 1 30,3.22 ha,6.238 ha,W76 40 25,-12.025000,-76.673611
112,1459-113,PE-XP-36/S-2011,Peru,S12 2 11,89.16 ha,—,W76 42 11,-12.036389,-76.703056
113,1459-114,PE-XP-37/C-2011,Peru,S12 2 19,1.79 ha,67.339 ha,W76 43 15,-12.038611,-76.720833
114,1459-115,PE-XP-38/S-2011,Peru,S12 4 50,10.26 ha,—,W76 46 28,-12.080556,-76.774444
115,1459-116,PE-XP-39/S-2011,Peru,S12 5 1,32.81 ha,—,W76 45 56,-12.083611,-76.765556
116,1459-117,PE-XP-40/CS-2011,Peru,S12 15 12.08,460.31 ha,"1,829.26 ha",W76 54 16.09,-12.253356,-76.904469
117,1459-118,PE-HH-41/CS-2011,Peru,S9 53 8,796.32 ha,"4,856.44 ha",W76 48 29,-9.885556,-76.808056
118,1459-119,PE-HH-42/CS-2011,Peru,S9 51 29,10.57 ha,504.01 ha,W76 51 5,-9.858056,-76.851389
119,1459-120,PE-HH-43/CS-2011,Peru,S9 46 44,4.23 ha,508.013 ha,W76 53 24,-9.778889,-76.890000
120,1459-121,PE-HH-44/CS-2011,Peru,S9 40 57,24.27 ha,"1,743.418 ha",W76 51 14,-9.682500,-76.853889
121,1459-122,PE-HH-45/CS-2011,Peru,S9 37 59.99,32.96 ha,NaN,W76 57 0,-9.633331,-76.950000
122,1459-123,PE-HH-46/CS-2011,Peru,S9 32 54,13.29 ha,281.808 ha,W76 59 10,-9.548333,-76.986111
123,1459-124,PE-HH-47/CS-2011,Peru,S9 30 52,4.47 ha,85.039 ha,W77 1 14,-9.514444,-77.020556
124,1459-125,PE-HH-48/CS-2011,Peru,S9 28 59.99,3.447 ha,157.621 ha,W77 1 59.99,-9.483331,-77.033331
125,1459-126,PE-HH-49/CS-2011,Peru,S9 27 55,10.5 ha,"4,262.694 ha",W77 4 17,-9.465278,-77.071389
126,1459-127,PE-HH-50/C-2011,Peru,S9 25 59.99,2.77 ha,NaN,W77 4 59.99,-9.433331,-77.083331
127,1459-128,PE-HH-51/CS-2011,Peru,S9 16 8,6.43 ha,"1,516.547 ha",W77 9 37,-9.268889,-77.160278
128,1459-129,PE-HH-52/CS-2011,Peru,S9 7 14,19.99 ha,528.729 ha,W77 12 29,-9.120556,-77.208056
129,1459-130,PE-HH-53/CS-2011,Peru,S9 4 0,14.05 ha,NaN,W77 13 59.99,-9.066667,-77.233331
130,1459-131,PE-HH-54/C-2011,Peru,S8 54 20,4.94 ha,275.69 ha,W77 19 42,-8.905556,-77.328333
131,1459-132,PE-HH-55/C-2011,Peru,S8 50 44,6.15 ha,216.446 ha,W77 22 49,-8.845556,-77.380278
132,1459-133,PE-HH-56/CS-2011,Peru,S8 45 59,15.45 ha,486.691 ha,W77 27 3,-8.766389,-77.450833
133,1459-134,PE-HH-57/CS-2011,Peru,S8 23 46,15.25 ha,387.392 ha,W77 46 21,-8.396111,-77.772500
134,1459-135,PE-HH-58/CS-2011,Peru,S8 19 48,4.41 ha,246.522 ha,W77 49 10,-8.330000,-77.819444
135,1459-136,PE-HH-59/CS-2011,Peru,S7 56 15,3.98 ha,"1,266.603 ha",W78 0 44,-7.937500,-78.012222
136,1459-137,PE-ALP-60/CS-2011,Peru,S4 42 17,37.22 ha,"1,502.79 ha",W79 34 27,-4.704722,-79.574167